// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: daily_inspections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDailyInspections = `-- name: CountDailyInspections :one
SELECT COUNT(*) as count
FROM vehicle_daily_inspections
WHERE ($1::date IS NULL OR inspection_date >= $1)
AND ($2::date IS NULL OR inspection_date <= $2)
AND ($3::text IS NULL OR overall_status = $3)
`

type CountDailyInspectionsParams struct {
	Column1 pgtype.Date `json:"column_1"`
	Column2 pgtype.Date `json:"column_2"`
	Column3 string      `json:"column_3"`
}

// 日常点検記録数をカウント
func (q *Queries) CountDailyInspections(ctx context.Context, arg CountDailyInspectionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDailyInspections, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDailyInspection = `-- name: CreateDailyInspection :one

INSERT INTO vehicle_daily_inspections (
    vehicle_id,
    driver_id,
    inspection_date,
    inspection_time,
    odometer_reading,
    engine_oil_level,
    coolant_level,
    brake_fluid_level,
    washer_fluid_level,
    tire_pressure_fl,
    tire_pressure_fr,
    tire_pressure_rl,
    tire_pressure_rr,
    tire_tread_depth,
    headlights,
    tail_lights,
    brake_lights,
    turn_signals,
    hazard_lights,
    windshield_wipers,
    horn,
    mirrors,
    seat_belt,
    body_damage,
    overall_status,
    abnormality_description,
    action_taken,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
    $21, $22, $23, $24, $25, $26, $27, $28
) RETURNING id, vehicle_id, driver_id, inspection_date, inspection_time, inspection_type, odometer_reading, engine_oil_level, coolant_level, brake_fluid_level, washer_fluid_level, battery_condition, engine_noise, tire_pressure_fl, tire_pressure_fr, tire_pressure_rl, tire_pressure_rr, tire_tread_depth, tire_damage, wheel_nuts, headlights, tail_lights, brake_lights, turn_signals, hazard_lights, clearance_lights, foot_brake_operation, parking_brake_operation, brake_effectiveness, air_brake_pressure, steering_operation, steering_play, clutch_operation, accelerator_operation, gear_shift_operation, windshield_wipers, horn, mirrors, windows_windshield, seat_belt, speedometer, cargo_bed_condition, loading_platform, tailgate_operation, body_damage, fuel_leak, oil_leak, water_leak, overall_status, abnormality_found, abnormality_description, action_taken, repair_required, repair_scheduled_date, weather_condition, temperature, notes, confirmed_by, confirmed_at, created_at, updated_at
`

type CreateDailyInspectionParams struct {
	VehicleID              int32       `json:"vehicle_id"`
	DriverID               int32       `json:"driver_id"`
	InspectionDate         pgtype.Date `json:"inspection_date"`
	InspectionTime         pgtype.Time `json:"inspection_time"`
	OdometerReading        *int32      `json:"odometer_reading"`
	EngineOilLevel         *string     `json:"engine_oil_level"`
	CoolantLevel           *string     `json:"coolant_level"`
	BrakeFluidLevel        *string     `json:"brake_fluid_level"`
	WasherFluidLevel       *string     `json:"washer_fluid_level"`
	TirePressureFl         *string     `json:"tire_pressure_fl"`
	TirePressureFr         *string     `json:"tire_pressure_fr"`
	TirePressureRl         *string     `json:"tire_pressure_rl"`
	TirePressureRr         *string     `json:"tire_pressure_rr"`
	TireTreadDepth         *string     `json:"tire_tread_depth"`
	Headlights             *string     `json:"headlights"`
	TailLights             *string     `json:"tail_lights"`
	BrakeLights            *string     `json:"brake_lights"`
	TurnSignals            *string     `json:"turn_signals"`
	HazardLights           *string     `json:"hazard_lights"`
	WindshieldWipers       *string     `json:"windshield_wipers"`
	Horn                   *string     `json:"horn"`
	Mirrors                *string     `json:"mirrors"`
	SeatBelt               *string     `json:"seat_belt"`
	BodyDamage             *string     `json:"body_damage"`
	OverallStatus          string      `json:"overall_status"`
	AbnormalityDescription *string     `json:"abnormality_description"`
	ActionTaken            *string     `json:"action_taken"`
	Notes                  *string     `json:"notes"`
}

// ==============================
// 日常点検クエリ
// ==============================
// 日常点検記録を登録
func (q *Queries) CreateDailyInspection(ctx context.Context, arg CreateDailyInspectionParams) (VehicleDailyInspection, error) {
	row := q.db.QueryRow(ctx, createDailyInspection,
		arg.VehicleID,
		arg.DriverID,
		arg.InspectionDate,
		arg.InspectionTime,
		arg.OdometerReading,
		arg.EngineOilLevel,
		arg.CoolantLevel,
		arg.BrakeFluidLevel,
		arg.WasherFluidLevel,
		arg.TirePressureFl,
		arg.TirePressureFr,
		arg.TirePressureRl,
		arg.TirePressureRr,
		arg.TireTreadDepth,
		arg.Headlights,
		arg.TailLights,
		arg.BrakeLights,
		arg.TurnSignals,
		arg.HazardLights,
		arg.WindshieldWipers,
		arg.Horn,
		arg.Mirrors,
		arg.SeatBelt,
		arg.BodyDamage,
		arg.OverallStatus,
		arg.AbnormalityDescription,
		arg.ActionTaken,
		arg.Notes,
	)
	var i VehicleDailyInspection
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.DriverID,
		&i.InspectionDate,
		&i.InspectionTime,
		&i.InspectionType,
		&i.OdometerReading,
		&i.EngineOilLevel,
		&i.CoolantLevel,
		&i.BrakeFluidLevel,
		&i.WasherFluidLevel,
		&i.BatteryCondition,
		&i.EngineNoise,
		&i.TirePressureFl,
		&i.TirePressureFr,
		&i.TirePressureRl,
		&i.TirePressureRr,
		&i.TireTreadDepth,
		&i.TireDamage,
		&i.WheelNuts,
		&i.Headlights,
		&i.TailLights,
		&i.BrakeLights,
		&i.TurnSignals,
		&i.HazardLights,
		&i.ClearanceLights,
		&i.FootBrakeOperation,
		&i.ParkingBrakeOperation,
		&i.BrakeEffectiveness,
		&i.AirBrakePressure,
		&i.SteeringOperation,
		&i.SteeringPlay,
		&i.ClutchOperation,
		&i.AcceleratorOperation,
		&i.GearShiftOperation,
		&i.WindshieldWipers,
		&i.Horn,
		&i.Mirrors,
		&i.WindowsWindshield,
		&i.SeatBelt,
		&i.Speedometer,
		&i.CargoBedCondition,
		&i.LoadingPlatform,
		&i.TailgateOperation,
		&i.BodyDamage,
		&i.FuelLeak,
		&i.OilLeak,
		&i.WaterLeak,
		&i.OverallStatus,
		&i.AbnormalityFound,
		&i.AbnormalityDescription,
		&i.ActionTaken,
		&i.RepairRequired,
		&i.RepairScheduledDate,
		&i.WeatherCondition,
		&i.Temperature,
		&i.Notes,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDailyInspection = `-- name: GetDailyInspection :one
SELECT 
    di.id, di.vehicle_id, di.driver_id, di.inspection_date, di.inspection_time, di.inspection_type, di.odometer_reading, di.engine_oil_level, di.coolant_level, di.brake_fluid_level, di.washer_fluid_level, di.battery_condition, di.engine_noise, di.tire_pressure_fl, di.tire_pressure_fr, di.tire_pressure_rl, di.tire_pressure_rr, di.tire_tread_depth, di.tire_damage, di.wheel_nuts, di.headlights, di.tail_lights, di.brake_lights, di.turn_signals, di.hazard_lights, di.clearance_lights, di.foot_brake_operation, di.parking_brake_operation, di.brake_effectiveness, di.air_brake_pressure, di.steering_operation, di.steering_play, di.clutch_operation, di.accelerator_operation, di.gear_shift_operation, di.windshield_wipers, di.horn, di.mirrors, di.windows_windshield, di.seat_belt, di.speedometer, di.cargo_bed_condition, di.loading_platform, di.tailgate_operation, di.body_damage, di.fuel_leak, di.oil_leak, di.water_leak, di.overall_status, di.abnormality_found, di.abnormality_description, di.action_taken, di.repair_required, di.repair_scheduled_date, di.weather_condition, di.temperature, di.notes, di.confirmed_by, di.confirmed_at, di.created_at, di.updated_at,
    v.vehicle_number,
    v.vehicle_name,
    e.last_name || ' ' || e.first_name as driver_name
FROM vehicle_daily_inspections di
JOIN vehicles v ON di.vehicle_id = v.id
LEFT JOIN employees e ON di.driver_id = e.id
WHERE di.id = $1
`

type GetDailyInspectionRow struct {
	ID                     int32              `json:"id"`
	VehicleID              int32              `json:"vehicle_id"`
	DriverID               int32              `json:"driver_id"`
	InspectionDate         pgtype.Date        `json:"inspection_date"`
	InspectionTime         pgtype.Time        `json:"inspection_time"`
	InspectionType         *string            `json:"inspection_type"`
	OdometerReading        *int32             `json:"odometer_reading"`
	EngineOilLevel         *string            `json:"engine_oil_level"`
	CoolantLevel           *string            `json:"coolant_level"`
	BrakeFluidLevel        *string            `json:"brake_fluid_level"`
	WasherFluidLevel       *string            `json:"washer_fluid_level"`
	BatteryCondition       *string            `json:"battery_condition"`
	EngineNoise            *string            `json:"engine_noise"`
	TirePressureFl         *string            `json:"tire_pressure_fl"`
	TirePressureFr         *string            `json:"tire_pressure_fr"`
	TirePressureRl         *string            `json:"tire_pressure_rl"`
	TirePressureRr         *string            `json:"tire_pressure_rr"`
	TireTreadDepth         *string            `json:"tire_tread_depth"`
	TireDamage             *string            `json:"tire_damage"`
	WheelNuts              *string            `json:"wheel_nuts"`
	Headlights             *string            `json:"headlights"`
	TailLights             *string            `json:"tail_lights"`
	BrakeLights            *string            `json:"brake_lights"`
	TurnSignals            *string            `json:"turn_signals"`
	HazardLights           *string            `json:"hazard_lights"`
	ClearanceLights        *string            `json:"clearance_lights"`
	FootBrakeOperation     *string            `json:"foot_brake_operation"`
	ParkingBrakeOperation  *string            `json:"parking_brake_operation"`
	BrakeEffectiveness     *string            `json:"brake_effectiveness"`
	AirBrakePressure       *string            `json:"air_brake_pressure"`
	SteeringOperation      *string            `json:"steering_operation"`
	SteeringPlay           *string            `json:"steering_play"`
	ClutchOperation        *string            `json:"clutch_operation"`
	AcceleratorOperation   *string            `json:"accelerator_operation"`
	GearShiftOperation     *string            `json:"gear_shift_operation"`
	WindshieldWipers       *string            `json:"windshield_wipers"`
	Horn                   *string            `json:"horn"`
	Mirrors                *string            `json:"mirrors"`
	WindowsWindshield      *string            `json:"windows_windshield"`
	SeatBelt               *string            `json:"seat_belt"`
	Speedometer            *string            `json:"speedometer"`
	CargoBedCondition      *string            `json:"cargo_bed_condition"`
	LoadingPlatform        *string            `json:"loading_platform"`
	TailgateOperation      *string            `json:"tailgate_operation"`
	BodyDamage             *string            `json:"body_damage"`
	FuelLeak               *string            `json:"fuel_leak"`
	OilLeak                *string            `json:"oil_leak"`
	WaterLeak              *string            `json:"water_leak"`
	OverallStatus          string             `json:"overall_status"`
	AbnormalityFound       *bool              `json:"abnormality_found"`
	AbnormalityDescription *string            `json:"abnormality_description"`
	ActionTaken            *string            `json:"action_taken"`
	RepairRequired         *bool              `json:"repair_required"`
	RepairScheduledDate    pgtype.Date        `json:"repair_scheduled_date"`
	WeatherCondition       *string            `json:"weather_condition"`
	Temperature            pgtype.Numeric     `json:"temperature"`
	Notes                  *string            `json:"notes"`
	ConfirmedBy            *int32             `json:"confirmed_by"`
	ConfirmedAt            pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	VehicleNumber          string             `json:"vehicle_number"`
	VehicleName            *string            `json:"vehicle_name"`
	DriverName             interface{}        `json:"driver_name"`
}

// 日常点検記録を取得
func (q *Queries) GetDailyInspection(ctx context.Context, id int32) (GetDailyInspectionRow, error) {
	row := q.db.QueryRow(ctx, getDailyInspection, id)
	var i GetDailyInspectionRow
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.DriverID,
		&i.InspectionDate,
		&i.InspectionTime,
		&i.InspectionType,
		&i.OdometerReading,
		&i.EngineOilLevel,
		&i.CoolantLevel,
		&i.BrakeFluidLevel,
		&i.WasherFluidLevel,
		&i.BatteryCondition,
		&i.EngineNoise,
		&i.TirePressureFl,
		&i.TirePressureFr,
		&i.TirePressureRl,
		&i.TirePressureRr,
		&i.TireTreadDepth,
		&i.TireDamage,
		&i.WheelNuts,
		&i.Headlights,
		&i.TailLights,
		&i.BrakeLights,
		&i.TurnSignals,
		&i.HazardLights,
		&i.ClearanceLights,
		&i.FootBrakeOperation,
		&i.ParkingBrakeOperation,
		&i.BrakeEffectiveness,
		&i.AirBrakePressure,
		&i.SteeringOperation,
		&i.SteeringPlay,
		&i.ClutchOperation,
		&i.AcceleratorOperation,
		&i.GearShiftOperation,
		&i.WindshieldWipers,
		&i.Horn,
		&i.Mirrors,
		&i.WindowsWindshield,
		&i.SeatBelt,
		&i.Speedometer,
		&i.CargoBedCondition,
		&i.LoadingPlatform,
		&i.TailgateOperation,
		&i.BodyDamage,
		&i.FuelLeak,
		&i.OilLeak,
		&i.WaterLeak,
		&i.OverallStatus,
		&i.AbnormalityFound,
		&i.AbnormalityDescription,
		&i.ActionTaken,
		&i.RepairRequired,
		&i.RepairScheduledDate,
		&i.WeatherCondition,
		&i.Temperature,
		&i.Notes,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.VehicleNumber,
		&i.VehicleName,
		&i.DriverName,
	)
	return i, err
}

const getDefectiveInspections = `-- name: GetDefectiveInspections :many
SELECT 
    di.id, di.vehicle_id, di.driver_id, di.inspection_date, di.inspection_time, di.inspection_type, di.odometer_reading, di.engine_oil_level, di.coolant_level, di.brake_fluid_level, di.washer_fluid_level, di.battery_condition, di.engine_noise, di.tire_pressure_fl, di.tire_pressure_fr, di.tire_pressure_rl, di.tire_pressure_rr, di.tire_tread_depth, di.tire_damage, di.wheel_nuts, di.headlights, di.tail_lights, di.brake_lights, di.turn_signals, di.hazard_lights, di.clearance_lights, di.foot_brake_operation, di.parking_brake_operation, di.brake_effectiveness, di.air_brake_pressure, di.steering_operation, di.steering_play, di.clutch_operation, di.accelerator_operation, di.gear_shift_operation, di.windshield_wipers, di.horn, di.mirrors, di.windows_windshield, di.seat_belt, di.speedometer, di.cargo_bed_condition, di.loading_platform, di.tailgate_operation, di.body_damage, di.fuel_leak, di.oil_leak, di.water_leak, di.overall_status, di.abnormality_found, di.abnormality_description, di.action_taken, di.repair_required, di.repair_scheduled_date, di.weather_condition, di.temperature, di.notes, di.confirmed_by, di.confirmed_at, di.created_at, di.updated_at,
    v.vehicle_number,
    v.vehicle_name,
    e.last_name || ' ' || e.first_name as driver_name
FROM vehicle_daily_inspections di
JOIN vehicles v ON di.vehicle_id = v.id
LEFT JOIN employees e ON di.driver_id = e.id
WHERE di.overall_status IN ('要注意', '整備必要', '運行不可')
ORDER BY di.inspection_date DESC
`

type GetDefectiveInspectionsRow struct {
	ID                     int32              `json:"id"`
	VehicleID              int32              `json:"vehicle_id"`
	DriverID               int32              `json:"driver_id"`
	InspectionDate         pgtype.Date        `json:"inspection_date"`
	InspectionTime         pgtype.Time        `json:"inspection_time"`
	InspectionType         *string            `json:"inspection_type"`
	OdometerReading        *int32             `json:"odometer_reading"`
	EngineOilLevel         *string            `json:"engine_oil_level"`
	CoolantLevel           *string            `json:"coolant_level"`
	BrakeFluidLevel        *string            `json:"brake_fluid_level"`
	WasherFluidLevel       *string            `json:"washer_fluid_level"`
	BatteryCondition       *string            `json:"battery_condition"`
	EngineNoise            *string            `json:"engine_noise"`
	TirePressureFl         *string            `json:"tire_pressure_fl"`
	TirePressureFr         *string            `json:"tire_pressure_fr"`
	TirePressureRl         *string            `json:"tire_pressure_rl"`
	TirePressureRr         *string            `json:"tire_pressure_rr"`
	TireTreadDepth         *string            `json:"tire_tread_depth"`
	TireDamage             *string            `json:"tire_damage"`
	WheelNuts              *string            `json:"wheel_nuts"`
	Headlights             *string            `json:"headlights"`
	TailLights             *string            `json:"tail_lights"`
	BrakeLights            *string            `json:"brake_lights"`
	TurnSignals            *string            `json:"turn_signals"`
	HazardLights           *string            `json:"hazard_lights"`
	ClearanceLights        *string            `json:"clearance_lights"`
	FootBrakeOperation     *string            `json:"foot_brake_operation"`
	ParkingBrakeOperation  *string            `json:"parking_brake_operation"`
	BrakeEffectiveness     *string            `json:"brake_effectiveness"`
	AirBrakePressure       *string            `json:"air_brake_pressure"`
	SteeringOperation      *string            `json:"steering_operation"`
	SteeringPlay           *string            `json:"steering_play"`
	ClutchOperation        *string            `json:"clutch_operation"`
	AcceleratorOperation   *string            `json:"accelerator_operation"`
	GearShiftOperation     *string            `json:"gear_shift_operation"`
	WindshieldWipers       *string            `json:"windshield_wipers"`
	Horn                   *string            `json:"horn"`
	Mirrors                *string            `json:"mirrors"`
	WindowsWindshield      *string            `json:"windows_windshield"`
	SeatBelt               *string            `json:"seat_belt"`
	Speedometer            *string            `json:"speedometer"`
	CargoBedCondition      *string            `json:"cargo_bed_condition"`
	LoadingPlatform        *string            `json:"loading_platform"`
	TailgateOperation      *string            `json:"tailgate_operation"`
	BodyDamage             *string            `json:"body_damage"`
	FuelLeak               *string            `json:"fuel_leak"`
	OilLeak                *string            `json:"oil_leak"`
	WaterLeak              *string            `json:"water_leak"`
	OverallStatus          string             `json:"overall_status"`
	AbnormalityFound       *bool              `json:"abnormality_found"`
	AbnormalityDescription *string            `json:"abnormality_description"`
	ActionTaken            *string            `json:"action_taken"`
	RepairRequired         *bool              `json:"repair_required"`
	RepairScheduledDate    pgtype.Date        `json:"repair_scheduled_date"`
	WeatherCondition       *string            `json:"weather_condition"`
	Temperature            pgtype.Numeric     `json:"temperature"`
	Notes                  *string            `json:"notes"`
	ConfirmedBy            *int32             `json:"confirmed_by"`
	ConfirmedAt            pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	VehicleNumber          string             `json:"vehicle_number"`
	VehicleName            *string            `json:"vehicle_name"`
	DriverName             interface{}        `json:"driver_name"`
}

// 不良のある点検記録一覧
func (q *Queries) GetDefectiveInspections(ctx context.Context) ([]GetDefectiveInspectionsRow, error) {
	rows, err := q.db.Query(ctx, getDefectiveInspections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDefectiveInspectionsRow{}
	for rows.Next() {
		var i GetDefectiveInspectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.DriverID,
			&i.InspectionDate,
			&i.InspectionTime,
			&i.InspectionType,
			&i.OdometerReading,
			&i.EngineOilLevel,
			&i.CoolantLevel,
			&i.BrakeFluidLevel,
			&i.WasherFluidLevel,
			&i.BatteryCondition,
			&i.EngineNoise,
			&i.TirePressureFl,
			&i.TirePressureFr,
			&i.TirePressureRl,
			&i.TirePressureRr,
			&i.TireTreadDepth,
			&i.TireDamage,
			&i.WheelNuts,
			&i.Headlights,
			&i.TailLights,
			&i.BrakeLights,
			&i.TurnSignals,
			&i.HazardLights,
			&i.ClearanceLights,
			&i.FootBrakeOperation,
			&i.ParkingBrakeOperation,
			&i.BrakeEffectiveness,
			&i.AirBrakePressure,
			&i.SteeringOperation,
			&i.SteeringPlay,
			&i.ClutchOperation,
			&i.AcceleratorOperation,
			&i.GearShiftOperation,
			&i.WindshieldWipers,
			&i.Horn,
			&i.Mirrors,
			&i.WindowsWindshield,
			&i.SeatBelt,
			&i.Speedometer,
			&i.CargoBedCondition,
			&i.LoadingPlatform,
			&i.TailgateOperation,
			&i.BodyDamage,
			&i.FuelLeak,
			&i.OilLeak,
			&i.WaterLeak,
			&i.OverallStatus,
			&i.AbnormalityFound,
			&i.AbnormalityDescription,
			&i.ActionTaken,
			&i.RepairRequired,
			&i.RepairScheduledDate,
			&i.WeatherCondition,
			&i.Temperature,
			&i.Notes,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VehicleNumber,
			&i.VehicleName,
			&i.DriverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestInspectionByVehicle = `-- name: GetLatestInspectionByVehicle :one
SELECT 
    di.id, di.vehicle_id, di.driver_id, di.inspection_date, di.inspection_time, di.inspection_type, di.odometer_reading, di.engine_oil_level, di.coolant_level, di.brake_fluid_level, di.washer_fluid_level, di.battery_condition, di.engine_noise, di.tire_pressure_fl, di.tire_pressure_fr, di.tire_pressure_rl, di.tire_pressure_rr, di.tire_tread_depth, di.tire_damage, di.wheel_nuts, di.headlights, di.tail_lights, di.brake_lights, di.turn_signals, di.hazard_lights, di.clearance_lights, di.foot_brake_operation, di.parking_brake_operation, di.brake_effectiveness, di.air_brake_pressure, di.steering_operation, di.steering_play, di.clutch_operation, di.accelerator_operation, di.gear_shift_operation, di.windshield_wipers, di.horn, di.mirrors, di.windows_windshield, di.seat_belt, di.speedometer, di.cargo_bed_condition, di.loading_platform, di.tailgate_operation, di.body_damage, di.fuel_leak, di.oil_leak, di.water_leak, di.overall_status, di.abnormality_found, di.abnormality_description, di.action_taken, di.repair_required, di.repair_scheduled_date, di.weather_condition, di.temperature, di.notes, di.confirmed_by, di.confirmed_at, di.created_at, di.updated_at,
    e.last_name || ' ' || e.first_name as driver_name
FROM vehicle_daily_inspections di
LEFT JOIN employees e ON di.driver_id = e.id
WHERE di.vehicle_id = $1
ORDER BY di.inspection_date DESC, di.inspection_time DESC
LIMIT 1
`

type GetLatestInspectionByVehicleRow struct {
	ID                     int32              `json:"id"`
	VehicleID              int32              `json:"vehicle_id"`
	DriverID               int32              `json:"driver_id"`
	InspectionDate         pgtype.Date        `json:"inspection_date"`
	InspectionTime         pgtype.Time        `json:"inspection_time"`
	InspectionType         *string            `json:"inspection_type"`
	OdometerReading        *int32             `json:"odometer_reading"`
	EngineOilLevel         *string            `json:"engine_oil_level"`
	CoolantLevel           *string            `json:"coolant_level"`
	BrakeFluidLevel        *string            `json:"brake_fluid_level"`
	WasherFluidLevel       *string            `json:"washer_fluid_level"`
	BatteryCondition       *string            `json:"battery_condition"`
	EngineNoise            *string            `json:"engine_noise"`
	TirePressureFl         *string            `json:"tire_pressure_fl"`
	TirePressureFr         *string            `json:"tire_pressure_fr"`
	TirePressureRl         *string            `json:"tire_pressure_rl"`
	TirePressureRr         *string            `json:"tire_pressure_rr"`
	TireTreadDepth         *string            `json:"tire_tread_depth"`
	TireDamage             *string            `json:"tire_damage"`
	WheelNuts              *string            `json:"wheel_nuts"`
	Headlights             *string            `json:"headlights"`
	TailLights             *string            `json:"tail_lights"`
	BrakeLights            *string            `json:"brake_lights"`
	TurnSignals            *string            `json:"turn_signals"`
	HazardLights           *string            `json:"hazard_lights"`
	ClearanceLights        *string            `json:"clearance_lights"`
	FootBrakeOperation     *string            `json:"foot_brake_operation"`
	ParkingBrakeOperation  *string            `json:"parking_brake_operation"`
	BrakeEffectiveness     *string            `json:"brake_effectiveness"`
	AirBrakePressure       *string            `json:"air_brake_pressure"`
	SteeringOperation      *string            `json:"steering_operation"`
	SteeringPlay           *string            `json:"steering_play"`
	ClutchOperation        *string            `json:"clutch_operation"`
	AcceleratorOperation   *string            `json:"accelerator_operation"`
	GearShiftOperation     *string            `json:"gear_shift_operation"`
	WindshieldWipers       *string            `json:"windshield_wipers"`
	Horn                   *string            `json:"horn"`
	Mirrors                *string            `json:"mirrors"`
	WindowsWindshield      *string            `json:"windows_windshield"`
	SeatBelt               *string            `json:"seat_belt"`
	Speedometer            *string            `json:"speedometer"`
	CargoBedCondition      *string            `json:"cargo_bed_condition"`
	LoadingPlatform        *string            `json:"loading_platform"`
	TailgateOperation      *string            `json:"tailgate_operation"`
	BodyDamage             *string            `json:"body_damage"`
	FuelLeak               *string            `json:"fuel_leak"`
	OilLeak                *string            `json:"oil_leak"`
	WaterLeak              *string            `json:"water_leak"`
	OverallStatus          string             `json:"overall_status"`
	AbnormalityFound       *bool              `json:"abnormality_found"`
	AbnormalityDescription *string            `json:"abnormality_description"`
	ActionTaken            *string            `json:"action_taken"`
	RepairRequired         *bool              `json:"repair_required"`
	RepairScheduledDate    pgtype.Date        `json:"repair_scheduled_date"`
	WeatherCondition       *string            `json:"weather_condition"`
	Temperature            pgtype.Numeric     `json:"temperature"`
	Notes                  *string            `json:"notes"`
	ConfirmedBy            *int32             `json:"confirmed_by"`
	ConfirmedAt            pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DriverName             interface{}        `json:"driver_name"`
}

// 車両の最新点検記録を取得
func (q *Queries) GetLatestInspectionByVehicle(ctx context.Context, vehicleID int32) (GetLatestInspectionByVehicleRow, error) {
	row := q.db.QueryRow(ctx, getLatestInspectionByVehicle, vehicleID)
	var i GetLatestInspectionByVehicleRow
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.DriverID,
		&i.InspectionDate,
		&i.InspectionTime,
		&i.InspectionType,
		&i.OdometerReading,
		&i.EngineOilLevel,
		&i.CoolantLevel,
		&i.BrakeFluidLevel,
		&i.WasherFluidLevel,
		&i.BatteryCondition,
		&i.EngineNoise,
		&i.TirePressureFl,
		&i.TirePressureFr,
		&i.TirePressureRl,
		&i.TirePressureRr,
		&i.TireTreadDepth,
		&i.TireDamage,
		&i.WheelNuts,
		&i.Headlights,
		&i.TailLights,
		&i.BrakeLights,
		&i.TurnSignals,
		&i.HazardLights,
		&i.ClearanceLights,
		&i.FootBrakeOperation,
		&i.ParkingBrakeOperation,
		&i.BrakeEffectiveness,
		&i.AirBrakePressure,
		&i.SteeringOperation,
		&i.SteeringPlay,
		&i.ClutchOperation,
		&i.AcceleratorOperation,
		&i.GearShiftOperation,
		&i.WindshieldWipers,
		&i.Horn,
		&i.Mirrors,
		&i.WindowsWindshield,
		&i.SeatBelt,
		&i.Speedometer,
		&i.CargoBedCondition,
		&i.LoadingPlatform,
		&i.TailgateOperation,
		&i.BodyDamage,
		&i.FuelLeak,
		&i.OilLeak,
		&i.WaterLeak,
		&i.OverallStatus,
		&i.AbnormalityFound,
		&i.AbnormalityDescription,
		&i.ActionTaken,
		&i.RepairRequired,
		&i.RepairScheduledDate,
		&i.WeatherCondition,
		&i.Temperature,
		&i.Notes,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DriverName,
	)
	return i, err
}

const listDailyInspections = `-- name: ListDailyInspections :many
SELECT 
    di.id, di.vehicle_id, di.driver_id, di.inspection_date, di.inspection_time, di.inspection_type, di.odometer_reading, di.engine_oil_level, di.coolant_level, di.brake_fluid_level, di.washer_fluid_level, di.battery_condition, di.engine_noise, di.tire_pressure_fl, di.tire_pressure_fr, di.tire_pressure_rl, di.tire_pressure_rr, di.tire_tread_depth, di.tire_damage, di.wheel_nuts, di.headlights, di.tail_lights, di.brake_lights, di.turn_signals, di.hazard_lights, di.clearance_lights, di.foot_brake_operation, di.parking_brake_operation, di.brake_effectiveness, di.air_brake_pressure, di.steering_operation, di.steering_play, di.clutch_operation, di.accelerator_operation, di.gear_shift_operation, di.windshield_wipers, di.horn, di.mirrors, di.windows_windshield, di.seat_belt, di.speedometer, di.cargo_bed_condition, di.loading_platform, di.tailgate_operation, di.body_damage, di.fuel_leak, di.oil_leak, di.water_leak, di.overall_status, di.abnormality_found, di.abnormality_description, di.action_taken, di.repair_required, di.repair_scheduled_date, di.weather_condition, di.temperature, di.notes, di.confirmed_by, di.confirmed_at, di.created_at, di.updated_at,
    v.vehicle_number,
    v.vehicle_name,
    e.last_name || ' ' || e.first_name as driver_name
FROM vehicle_daily_inspections di
JOIN vehicles v ON di.vehicle_id = v.id
LEFT JOIN employees e ON di.driver_id = e.id
ORDER BY di.inspection_date DESC, di.inspection_time DESC
LIMIT $1 OFFSET $2
`

type ListDailyInspectionsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListDailyInspectionsRow struct {
	ID                     int32              `json:"id"`
	VehicleID              int32              `json:"vehicle_id"`
	DriverID               int32              `json:"driver_id"`
	InspectionDate         pgtype.Date        `json:"inspection_date"`
	InspectionTime         pgtype.Time        `json:"inspection_time"`
	InspectionType         *string            `json:"inspection_type"`
	OdometerReading        *int32             `json:"odometer_reading"`
	EngineOilLevel         *string            `json:"engine_oil_level"`
	CoolantLevel           *string            `json:"coolant_level"`
	BrakeFluidLevel        *string            `json:"brake_fluid_level"`
	WasherFluidLevel       *string            `json:"washer_fluid_level"`
	BatteryCondition       *string            `json:"battery_condition"`
	EngineNoise            *string            `json:"engine_noise"`
	TirePressureFl         *string            `json:"tire_pressure_fl"`
	TirePressureFr         *string            `json:"tire_pressure_fr"`
	TirePressureRl         *string            `json:"tire_pressure_rl"`
	TirePressureRr         *string            `json:"tire_pressure_rr"`
	TireTreadDepth         *string            `json:"tire_tread_depth"`
	TireDamage             *string            `json:"tire_damage"`
	WheelNuts              *string            `json:"wheel_nuts"`
	Headlights             *string            `json:"headlights"`
	TailLights             *string            `json:"tail_lights"`
	BrakeLights            *string            `json:"brake_lights"`
	TurnSignals            *string            `json:"turn_signals"`
	HazardLights           *string            `json:"hazard_lights"`
	ClearanceLights        *string            `json:"clearance_lights"`
	FootBrakeOperation     *string            `json:"foot_brake_operation"`
	ParkingBrakeOperation  *string            `json:"parking_brake_operation"`
	BrakeEffectiveness     *string            `json:"brake_effectiveness"`
	AirBrakePressure       *string            `json:"air_brake_pressure"`
	SteeringOperation      *string            `json:"steering_operation"`
	SteeringPlay           *string            `json:"steering_play"`
	ClutchOperation        *string            `json:"clutch_operation"`
	AcceleratorOperation   *string            `json:"accelerator_operation"`
	GearShiftOperation     *string            `json:"gear_shift_operation"`
	WindshieldWipers       *string            `json:"windshield_wipers"`
	Horn                   *string            `json:"horn"`
	Mirrors                *string            `json:"mirrors"`
	WindowsWindshield      *string            `json:"windows_windshield"`
	SeatBelt               *string            `json:"seat_belt"`
	Speedometer            *string            `json:"speedometer"`
	CargoBedCondition      *string            `json:"cargo_bed_condition"`
	LoadingPlatform        *string            `json:"loading_platform"`
	TailgateOperation      *string            `json:"tailgate_operation"`
	BodyDamage             *string            `json:"body_damage"`
	FuelLeak               *string            `json:"fuel_leak"`
	OilLeak                *string            `json:"oil_leak"`
	WaterLeak              *string            `json:"water_leak"`
	OverallStatus          string             `json:"overall_status"`
	AbnormalityFound       *bool              `json:"abnormality_found"`
	AbnormalityDescription *string            `json:"abnormality_description"`
	ActionTaken            *string            `json:"action_taken"`
	RepairRequired         *bool              `json:"repair_required"`
	RepairScheduledDate    pgtype.Date        `json:"repair_scheduled_date"`
	WeatherCondition       *string            `json:"weather_condition"`
	Temperature            pgtype.Numeric     `json:"temperature"`
	Notes                  *string            `json:"notes"`
	ConfirmedBy            *int32             `json:"confirmed_by"`
	ConfirmedAt            pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	VehicleNumber          string             `json:"vehicle_number"`
	VehicleName            *string            `json:"vehicle_name"`
	DriverName             interface{}        `json:"driver_name"`
}

// 日常点検記録一覧
func (q *Queries) ListDailyInspections(ctx context.Context, arg ListDailyInspectionsParams) ([]ListDailyInspectionsRow, error) {
	rows, err := q.db.Query(ctx, listDailyInspections, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyInspectionsRow{}
	for rows.Next() {
		var i ListDailyInspectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.DriverID,
			&i.InspectionDate,
			&i.InspectionTime,
			&i.InspectionType,
			&i.OdometerReading,
			&i.EngineOilLevel,
			&i.CoolantLevel,
			&i.BrakeFluidLevel,
			&i.WasherFluidLevel,
			&i.BatteryCondition,
			&i.EngineNoise,
			&i.TirePressureFl,
			&i.TirePressureFr,
			&i.TirePressureRl,
			&i.TirePressureRr,
			&i.TireTreadDepth,
			&i.TireDamage,
			&i.WheelNuts,
			&i.Headlights,
			&i.TailLights,
			&i.BrakeLights,
			&i.TurnSignals,
			&i.HazardLights,
			&i.ClearanceLights,
			&i.FootBrakeOperation,
			&i.ParkingBrakeOperation,
			&i.BrakeEffectiveness,
			&i.AirBrakePressure,
			&i.SteeringOperation,
			&i.SteeringPlay,
			&i.ClutchOperation,
			&i.AcceleratorOperation,
			&i.GearShiftOperation,
			&i.WindshieldWipers,
			&i.Horn,
			&i.Mirrors,
			&i.WindowsWindshield,
			&i.SeatBelt,
			&i.Speedometer,
			&i.CargoBedCondition,
			&i.LoadingPlatform,
			&i.TailgateOperation,
			&i.BodyDamage,
			&i.FuelLeak,
			&i.OilLeak,
			&i.WaterLeak,
			&i.OverallStatus,
			&i.AbnormalityFound,
			&i.AbnormalityDescription,
			&i.ActionTaken,
			&i.RepairRequired,
			&i.RepairScheduledDate,
			&i.WeatherCondition,
			&i.Temperature,
			&i.Notes,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VehicleNumber,
			&i.VehicleName,
			&i.DriverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyInspectionsByDate = `-- name: ListDailyInspectionsByDate :many
SELECT 
    di.id, di.vehicle_id, di.driver_id, di.inspection_date, di.inspection_time, di.inspection_type, di.odometer_reading, di.engine_oil_level, di.coolant_level, di.brake_fluid_level, di.washer_fluid_level, di.battery_condition, di.engine_noise, di.tire_pressure_fl, di.tire_pressure_fr, di.tire_pressure_rl, di.tire_pressure_rr, di.tire_tread_depth, di.tire_damage, di.wheel_nuts, di.headlights, di.tail_lights, di.brake_lights, di.turn_signals, di.hazard_lights, di.clearance_lights, di.foot_brake_operation, di.parking_brake_operation, di.brake_effectiveness, di.air_brake_pressure, di.steering_operation, di.steering_play, di.clutch_operation, di.accelerator_operation, di.gear_shift_operation, di.windshield_wipers, di.horn, di.mirrors, di.windows_windshield, di.seat_belt, di.speedometer, di.cargo_bed_condition, di.loading_platform, di.tailgate_operation, di.body_damage, di.fuel_leak, di.oil_leak, di.water_leak, di.overall_status, di.abnormality_found, di.abnormality_description, di.action_taken, di.repair_required, di.repair_scheduled_date, di.weather_condition, di.temperature, di.notes, di.confirmed_by, di.confirmed_at, di.created_at, di.updated_at,
    v.vehicle_number,
    v.vehicle_name,
    e.last_name || ' ' || e.first_name as driver_name
FROM vehicle_daily_inspections di
JOIN vehicles v ON di.vehicle_id = v.id
LEFT JOIN employees e ON di.driver_id = e.id
WHERE di.inspection_date = $1
ORDER BY di.inspection_time
`

type ListDailyInspectionsByDateRow struct {
	ID                     int32              `json:"id"`
	VehicleID              int32              `json:"vehicle_id"`
	DriverID               int32              `json:"driver_id"`
	InspectionDate         pgtype.Date        `json:"inspection_date"`
	InspectionTime         pgtype.Time        `json:"inspection_time"`
	InspectionType         *string            `json:"inspection_type"`
	OdometerReading        *int32             `json:"odometer_reading"`
	EngineOilLevel         *string            `json:"engine_oil_level"`
	CoolantLevel           *string            `json:"coolant_level"`
	BrakeFluidLevel        *string            `json:"brake_fluid_level"`
	WasherFluidLevel       *string            `json:"washer_fluid_level"`
	BatteryCondition       *string            `json:"battery_condition"`
	EngineNoise            *string            `json:"engine_noise"`
	TirePressureFl         *string            `json:"tire_pressure_fl"`
	TirePressureFr         *string            `json:"tire_pressure_fr"`
	TirePressureRl         *string            `json:"tire_pressure_rl"`
	TirePressureRr         *string            `json:"tire_pressure_rr"`
	TireTreadDepth         *string            `json:"tire_tread_depth"`
	TireDamage             *string            `json:"tire_damage"`
	WheelNuts              *string            `json:"wheel_nuts"`
	Headlights             *string            `json:"headlights"`
	TailLights             *string            `json:"tail_lights"`
	BrakeLights            *string            `json:"brake_lights"`
	TurnSignals            *string            `json:"turn_signals"`
	HazardLights           *string            `json:"hazard_lights"`
	ClearanceLights        *string            `json:"clearance_lights"`
	FootBrakeOperation     *string            `json:"foot_brake_operation"`
	ParkingBrakeOperation  *string            `json:"parking_brake_operation"`
	BrakeEffectiveness     *string            `json:"brake_effectiveness"`
	AirBrakePressure       *string            `json:"air_brake_pressure"`
	SteeringOperation      *string            `json:"steering_operation"`
	SteeringPlay           *string            `json:"steering_play"`
	ClutchOperation        *string            `json:"clutch_operation"`
	AcceleratorOperation   *string            `json:"accelerator_operation"`
	GearShiftOperation     *string            `json:"gear_shift_operation"`
	WindshieldWipers       *string            `json:"windshield_wipers"`
	Horn                   *string            `json:"horn"`
	Mirrors                *string            `json:"mirrors"`
	WindowsWindshield      *string            `json:"windows_windshield"`
	SeatBelt               *string            `json:"seat_belt"`
	Speedometer            *string            `json:"speedometer"`
	CargoBedCondition      *string            `json:"cargo_bed_condition"`
	LoadingPlatform        *string            `json:"loading_platform"`
	TailgateOperation      *string            `json:"tailgate_operation"`
	BodyDamage             *string            `json:"body_damage"`
	FuelLeak               *string            `json:"fuel_leak"`
	OilLeak                *string            `json:"oil_leak"`
	WaterLeak              *string            `json:"water_leak"`
	OverallStatus          string             `json:"overall_status"`
	AbnormalityFound       *bool              `json:"abnormality_found"`
	AbnormalityDescription *string            `json:"abnormality_description"`
	ActionTaken            *string            `json:"action_taken"`
	RepairRequired         *bool              `json:"repair_required"`
	RepairScheduledDate    pgtype.Date        `json:"repair_scheduled_date"`
	WeatherCondition       *string            `json:"weather_condition"`
	Temperature            pgtype.Numeric     `json:"temperature"`
	Notes                  *string            `json:"notes"`
	ConfirmedBy            *int32             `json:"confirmed_by"`
	ConfirmedAt            pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	VehicleNumber          string             `json:"vehicle_number"`
	VehicleName            *string            `json:"vehicle_name"`
	DriverName             interface{}        `json:"driver_name"`
}

// 日付別の日常点検記録
func (q *Queries) ListDailyInspectionsByDate(ctx context.Context, inspectionDate pgtype.Date) ([]ListDailyInspectionsByDateRow, error) {
	rows, err := q.db.Query(ctx, listDailyInspectionsByDate, inspectionDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyInspectionsByDateRow{}
	for rows.Next() {
		var i ListDailyInspectionsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.DriverID,
			&i.InspectionDate,
			&i.InspectionTime,
			&i.InspectionType,
			&i.OdometerReading,
			&i.EngineOilLevel,
			&i.CoolantLevel,
			&i.BrakeFluidLevel,
			&i.WasherFluidLevel,
			&i.BatteryCondition,
			&i.EngineNoise,
			&i.TirePressureFl,
			&i.TirePressureFr,
			&i.TirePressureRl,
			&i.TirePressureRr,
			&i.TireTreadDepth,
			&i.TireDamage,
			&i.WheelNuts,
			&i.Headlights,
			&i.TailLights,
			&i.BrakeLights,
			&i.TurnSignals,
			&i.HazardLights,
			&i.ClearanceLights,
			&i.FootBrakeOperation,
			&i.ParkingBrakeOperation,
			&i.BrakeEffectiveness,
			&i.AirBrakePressure,
			&i.SteeringOperation,
			&i.SteeringPlay,
			&i.ClutchOperation,
			&i.AcceleratorOperation,
			&i.GearShiftOperation,
			&i.WindshieldWipers,
			&i.Horn,
			&i.Mirrors,
			&i.WindowsWindshield,
			&i.SeatBelt,
			&i.Speedometer,
			&i.CargoBedCondition,
			&i.LoadingPlatform,
			&i.TailgateOperation,
			&i.BodyDamage,
			&i.FuelLeak,
			&i.OilLeak,
			&i.WaterLeak,
			&i.OverallStatus,
			&i.AbnormalityFound,
			&i.AbnormalityDescription,
			&i.ActionTaken,
			&i.RepairRequired,
			&i.RepairScheduledDate,
			&i.WeatherCondition,
			&i.Temperature,
			&i.Notes,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VehicleNumber,
			&i.VehicleName,
			&i.DriverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDailyInspectionsByVehicle = `-- name: ListDailyInspectionsByVehicle :many
SELECT 
    di.id, di.vehicle_id, di.driver_id, di.inspection_date, di.inspection_time, di.inspection_type, di.odometer_reading, di.engine_oil_level, di.coolant_level, di.brake_fluid_level, di.washer_fluid_level, di.battery_condition, di.engine_noise, di.tire_pressure_fl, di.tire_pressure_fr, di.tire_pressure_rl, di.tire_pressure_rr, di.tire_tread_depth, di.tire_damage, di.wheel_nuts, di.headlights, di.tail_lights, di.brake_lights, di.turn_signals, di.hazard_lights, di.clearance_lights, di.foot_brake_operation, di.parking_brake_operation, di.brake_effectiveness, di.air_brake_pressure, di.steering_operation, di.steering_play, di.clutch_operation, di.accelerator_operation, di.gear_shift_operation, di.windshield_wipers, di.horn, di.mirrors, di.windows_windshield, di.seat_belt, di.speedometer, di.cargo_bed_condition, di.loading_platform, di.tailgate_operation, di.body_damage, di.fuel_leak, di.oil_leak, di.water_leak, di.overall_status, di.abnormality_found, di.abnormality_description, di.action_taken, di.repair_required, di.repair_scheduled_date, di.weather_condition, di.temperature, di.notes, di.confirmed_by, di.confirmed_at, di.created_at, di.updated_at,
    e.last_name || ' ' || e.first_name as driver_name
FROM vehicle_daily_inspections di
LEFT JOIN employees e ON di.driver_id = e.id
WHERE di.vehicle_id = $1
ORDER BY di.inspection_date DESC, di.inspection_time DESC
LIMIT $2 OFFSET $3
`

type ListDailyInspectionsByVehicleParams struct {
	VehicleID int32 `json:"vehicle_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListDailyInspectionsByVehicleRow struct {
	ID                     int32              `json:"id"`
	VehicleID              int32              `json:"vehicle_id"`
	DriverID               int32              `json:"driver_id"`
	InspectionDate         pgtype.Date        `json:"inspection_date"`
	InspectionTime         pgtype.Time        `json:"inspection_time"`
	InspectionType         *string            `json:"inspection_type"`
	OdometerReading        *int32             `json:"odometer_reading"`
	EngineOilLevel         *string            `json:"engine_oil_level"`
	CoolantLevel           *string            `json:"coolant_level"`
	BrakeFluidLevel        *string            `json:"brake_fluid_level"`
	WasherFluidLevel       *string            `json:"washer_fluid_level"`
	BatteryCondition       *string            `json:"battery_condition"`
	EngineNoise            *string            `json:"engine_noise"`
	TirePressureFl         *string            `json:"tire_pressure_fl"`
	TirePressureFr         *string            `json:"tire_pressure_fr"`
	TirePressureRl         *string            `json:"tire_pressure_rl"`
	TirePressureRr         *string            `json:"tire_pressure_rr"`
	TireTreadDepth         *string            `json:"tire_tread_depth"`
	TireDamage             *string            `json:"tire_damage"`
	WheelNuts              *string            `json:"wheel_nuts"`
	Headlights             *string            `json:"headlights"`
	TailLights             *string            `json:"tail_lights"`
	BrakeLights            *string            `json:"brake_lights"`
	TurnSignals            *string            `json:"turn_signals"`
	HazardLights           *string            `json:"hazard_lights"`
	ClearanceLights        *string            `json:"clearance_lights"`
	FootBrakeOperation     *string            `json:"foot_brake_operation"`
	ParkingBrakeOperation  *string            `json:"parking_brake_operation"`
	BrakeEffectiveness     *string            `json:"brake_effectiveness"`
	AirBrakePressure       *string            `json:"air_brake_pressure"`
	SteeringOperation      *string            `json:"steering_operation"`
	SteeringPlay           *string            `json:"steering_play"`
	ClutchOperation        *string            `json:"clutch_operation"`
	AcceleratorOperation   *string            `json:"accelerator_operation"`
	GearShiftOperation     *string            `json:"gear_shift_operation"`
	WindshieldWipers       *string            `json:"windshield_wipers"`
	Horn                   *string            `json:"horn"`
	Mirrors                *string            `json:"mirrors"`
	WindowsWindshield      *string            `json:"windows_windshield"`
	SeatBelt               *string            `json:"seat_belt"`
	Speedometer            *string            `json:"speedometer"`
	CargoBedCondition      *string            `json:"cargo_bed_condition"`
	LoadingPlatform        *string            `json:"loading_platform"`
	TailgateOperation      *string            `json:"tailgate_operation"`
	BodyDamage             *string            `json:"body_damage"`
	FuelLeak               *string            `json:"fuel_leak"`
	OilLeak                *string            `json:"oil_leak"`
	WaterLeak              *string            `json:"water_leak"`
	OverallStatus          string             `json:"overall_status"`
	AbnormalityFound       *bool              `json:"abnormality_found"`
	AbnormalityDescription *string            `json:"abnormality_description"`
	ActionTaken            *string            `json:"action_taken"`
	RepairRequired         *bool              `json:"repair_required"`
	RepairScheduledDate    pgtype.Date        `json:"repair_scheduled_date"`
	WeatherCondition       *string            `json:"weather_condition"`
	Temperature            pgtype.Numeric     `json:"temperature"`
	Notes                  *string            `json:"notes"`
	ConfirmedBy            *int32             `json:"confirmed_by"`
	ConfirmedAt            pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	DriverName             interface{}        `json:"driver_name"`
}

// 車両別の日常点検記録
func (q *Queries) ListDailyInspectionsByVehicle(ctx context.Context, arg ListDailyInspectionsByVehicleParams) ([]ListDailyInspectionsByVehicleRow, error) {
	rows, err := q.db.Query(ctx, listDailyInspectionsByVehicle, arg.VehicleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDailyInspectionsByVehicleRow{}
	for rows.Next() {
		var i ListDailyInspectionsByVehicleRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.DriverID,
			&i.InspectionDate,
			&i.InspectionTime,
			&i.InspectionType,
			&i.OdometerReading,
			&i.EngineOilLevel,
			&i.CoolantLevel,
			&i.BrakeFluidLevel,
			&i.WasherFluidLevel,
			&i.BatteryCondition,
			&i.EngineNoise,
			&i.TirePressureFl,
			&i.TirePressureFr,
			&i.TirePressureRl,
			&i.TirePressureRr,
			&i.TireTreadDepth,
			&i.TireDamage,
			&i.WheelNuts,
			&i.Headlights,
			&i.TailLights,
			&i.BrakeLights,
			&i.TurnSignals,
			&i.HazardLights,
			&i.ClearanceLights,
			&i.FootBrakeOperation,
			&i.ParkingBrakeOperation,
			&i.BrakeEffectiveness,
			&i.AirBrakePressure,
			&i.SteeringOperation,
			&i.SteeringPlay,
			&i.ClutchOperation,
			&i.AcceleratorOperation,
			&i.GearShiftOperation,
			&i.WindshieldWipers,
			&i.Horn,
			&i.Mirrors,
			&i.WindowsWindshield,
			&i.SeatBelt,
			&i.Speedometer,
			&i.CargoBedCondition,
			&i.LoadingPlatform,
			&i.TailgateOperation,
			&i.BodyDamage,
			&i.FuelLeak,
			&i.OilLeak,
			&i.WaterLeak,
			&i.OverallStatus,
			&i.AbnormalityFound,
			&i.AbnormalityDescription,
			&i.ActionTaken,
			&i.RepairRequired,
			&i.RepairScheduledDate,
			&i.WeatherCondition,
			&i.Temperature,
			&i.Notes,
			&i.ConfirmedBy,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DriverName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDailyInspection = `-- name: UpdateDailyInspection :exec
UPDATE vehicle_daily_inspections
SET
    overall_status = COALESCE($1, overall_status),
    abnormality_description = COALESCE($2, abnormality_description),
    action_taken = COALESCE($3, action_taken),
    notes = COALESCE($4, notes),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $5
`

type UpdateDailyInspectionParams struct {
	OverallStatus          *string `json:"overall_status"`
	AbnormalityDescription *string `json:"abnormality_description"`
	ActionTaken            *string `json:"action_taken"`
	Notes                  *string `json:"notes"`
	ID                     int32   `json:"id"`
}

// 日常点検記録を更新
func (q *Queries) UpdateDailyInspection(ctx context.Context, arg UpdateDailyInspectionParams) error {
	_, err := q.db.Exec(ctx, updateDailyInspection,
		arg.OverallStatus,
		arg.AbnormalityDescription,
		arg.ActionTaken,
		arg.Notes,
		arg.ID,
	)
	return err
}
