// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEmployees = `-- name: CountEmployees :one
SELECT COUNT(*) as count
FROM employees
WHERE deleted_at IS NULL
AND ($1::boolean IS NULL OR is_active = $1)
`

// 従業員数をカウント
func (q *Queries) CountEmployees(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRow(ctx, countEmployees, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEmployee = `-- name: CreateEmployee :one

INSERT INTO employees (
    employee_code,
    last_name,
    first_name,
    last_name_kana,
    first_name_kana,
    legal_name,
    gender,
    birth_date,
    hire_date,
    office_id,
    job_type,
    employment_type,
    department,
    position,
    role_id,
    nationality,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
) RETURNING id, employee_code, employee_image_url, employee_photo_date, last_name, first_name, last_name_kana, first_name_kana, legal_name, gender, birth_date, hire_date, appointment_date, office_id, job_type, employment_type, department, position, retirement_date, retirement_reason, death_date, death_reason, driver_license_no, driver_license_type, driver_license_issue_date, driver_license_expiry, driver_license_image_url_front, driver_license_image_url_back, driving_disabled_date, driving_disabled_reason, nationality, visa_type, visa_expiry, role_id, password_hash, password_updated_at, failed_login_attempts, locked_until, last_login_at, is_active, created_at, updated_at, deleted_at
`

type CreateEmployeeParams struct {
	EmployeeCode   *string     `json:"employee_code"`
	LastName       string      `json:"last_name"`
	FirstName      string      `json:"first_name"`
	LastNameKana   *string     `json:"last_name_kana"`
	FirstNameKana  *string     `json:"first_name_kana"`
	LegalName      *string     `json:"legal_name"`
	Gender         *string     `json:"gender"`
	BirthDate      pgtype.Date `json:"birth_date"`
	HireDate       pgtype.Date `json:"hire_date"`
	OfficeID       *int32      `json:"office_id"`
	JobType        *string     `json:"job_type"`
	EmploymentType *string     `json:"employment_type"`
	Department     *string     `json:"department"`
	Position       *string     `json:"position"`
	RoleID         *int32      `json:"role_id"`
	Nationality    *string     `json:"nationality"`
	IsActive       *bool       `json:"is_active"`
}

// ==============================
// 従業員管理クエリ
// ==============================
// 従業員を新規登録
func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error) {
	row := q.db.QueryRow(ctx, createEmployee,
		arg.EmployeeCode,
		arg.LastName,
		arg.FirstName,
		arg.LastNameKana,
		arg.FirstNameKana,
		arg.LegalName,
		arg.Gender,
		arg.BirthDate,
		arg.HireDate,
		arg.OfficeID,
		arg.JobType,
		arg.EmploymentType,
		arg.Department,
		arg.Position,
		arg.RoleID,
		arg.Nationality,
		arg.IsActive,
	)
	var i Employee
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.EmployeeImageUrl,
		&i.EmployeePhotoDate,
		&i.LastName,
		&i.FirstName,
		&i.LastNameKana,
		&i.FirstNameKana,
		&i.LegalName,
		&i.Gender,
		&i.BirthDate,
		&i.HireDate,
		&i.AppointmentDate,
		&i.OfficeID,
		&i.JobType,
		&i.EmploymentType,
		&i.Department,
		&i.Position,
		&i.RetirementDate,
		&i.RetirementReason,
		&i.DeathDate,
		&i.DeathReason,
		&i.DriverLicenseNo,
		&i.DriverLicenseType,
		&i.DriverLicenseIssueDate,
		&i.DriverLicenseExpiry,
		&i.DriverLicenseImageUrlFront,
		&i.DriverLicenseImageUrlBack,
		&i.DrivingDisabledDate,
		&i.DrivingDisabledReason,
		&i.Nationality,
		&i.VisaType,
		&i.VisaExpiry,
		&i.RoleID,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteEmployee = `-- name: DeleteEmployee :exec
UPDATE employees
SET
    deleted_at = CURRENT_TIMESTAMP,
    is_active = false
WHERE id = $1
`

// 従業員を論理削除
func (q *Queries) DeleteEmployee(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}

const getEmployee = `-- name: GetEmployee :one
SELECT 
    e.id, e.employee_code, e.employee_image_url, e.employee_photo_date, e.last_name, e.first_name, e.last_name_kana, e.first_name_kana, e.legal_name, e.gender, e.birth_date, e.hire_date, e.appointment_date, e.office_id, e.job_type, e.employment_type, e.department, e.position, e.retirement_date, e.retirement_reason, e.death_date, e.death_reason, e.driver_license_no, e.driver_license_type, e.driver_license_issue_date, e.driver_license_expiry, e.driver_license_image_url_front, e.driver_license_image_url_back, e.driving_disabled_date, e.driving_disabled_reason, e.nationality, e.visa_type, e.visa_expiry, e.role_id, e.password_hash, e.password_updated_at, e.failed_login_attempts, e.locked_until, e.last_login_at, e.is_active, e.created_at, e.updated_at, e.deleted_at,
    o.office_name,
    r.name as role_name
FROM employees e
LEFT JOIN company_offices o ON e.office_id = o.id
LEFT JOIN m_roles r ON e.role_id = r.id
WHERE e.id = $1
AND e.deleted_at IS NULL
`

type GetEmployeeRow struct {
	ID                         int32              `json:"id"`
	EmployeeCode               *string            `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     *string            `json:"gender"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                *string            `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                 *string            `json:"office_name"`
	RoleName                   *string            `json:"role_name"`
}

// 従業員をIDで取得
func (q *Queries) GetEmployee(ctx context.Context, id int32) (GetEmployeeRow, error) {
	row := q.db.QueryRow(ctx, getEmployee, id)
	var i GetEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.EmployeeImageUrl,
		&i.EmployeePhotoDate,
		&i.LastName,
		&i.FirstName,
		&i.LastNameKana,
		&i.FirstNameKana,
		&i.LegalName,
		&i.Gender,
		&i.BirthDate,
		&i.HireDate,
		&i.AppointmentDate,
		&i.OfficeID,
		&i.JobType,
		&i.EmploymentType,
		&i.Department,
		&i.Position,
		&i.RetirementDate,
		&i.RetirementReason,
		&i.DeathDate,
		&i.DeathReason,
		&i.DriverLicenseNo,
		&i.DriverLicenseType,
		&i.DriverLicenseIssueDate,
		&i.DriverLicenseExpiry,
		&i.DriverLicenseImageUrlFront,
		&i.DriverLicenseImageUrlBack,
		&i.DrivingDisabledDate,
		&i.DrivingDisabledReason,
		&i.Nationality,
		&i.VisaType,
		&i.VisaExpiry,
		&i.RoleID,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeName,
		&i.RoleName,
	)
	return i, err
}

const getEmployeeByCode = `-- name: GetEmployeeByCode :one
SELECT 
    e.id, e.employee_code, e.employee_image_url, e.employee_photo_date, e.last_name, e.first_name, e.last_name_kana, e.first_name_kana, e.legal_name, e.gender, e.birth_date, e.hire_date, e.appointment_date, e.office_id, e.job_type, e.employment_type, e.department, e.position, e.retirement_date, e.retirement_reason, e.death_date, e.death_reason, e.driver_license_no, e.driver_license_type, e.driver_license_issue_date, e.driver_license_expiry, e.driver_license_image_url_front, e.driver_license_image_url_back, e.driving_disabled_date, e.driving_disabled_reason, e.nationality, e.visa_type, e.visa_expiry, e.role_id, e.password_hash, e.password_updated_at, e.failed_login_attempts, e.locked_until, e.last_login_at, e.is_active, e.created_at, e.updated_at, e.deleted_at,
    o.office_name,
    r.name as role_name
FROM employees e
LEFT JOIN company_offices o ON e.office_id = o.id
LEFT JOIN m_roles r ON e.role_id = r.id
WHERE e.employee_code = $1
AND e.deleted_at IS NULL
`

type GetEmployeeByCodeRow struct {
	ID                         int32              `json:"id"`
	EmployeeCode               *string            `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     *string            `json:"gender"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                *string            `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                 *string            `json:"office_name"`
	RoleName                   *string            `json:"role_name"`
}

// 従業員コードで取得
func (q *Queries) GetEmployeeByCode(ctx context.Context, employeeCode *string) (GetEmployeeByCodeRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeByCode, employeeCode)
	var i GetEmployeeByCodeRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.EmployeeImageUrl,
		&i.EmployeePhotoDate,
		&i.LastName,
		&i.FirstName,
		&i.LastNameKana,
		&i.FirstNameKana,
		&i.LegalName,
		&i.Gender,
		&i.BirthDate,
		&i.HireDate,
		&i.AppointmentDate,
		&i.OfficeID,
		&i.JobType,
		&i.EmploymentType,
		&i.Department,
		&i.Position,
		&i.RetirementDate,
		&i.RetirementReason,
		&i.DeathDate,
		&i.DeathReason,
		&i.DriverLicenseNo,
		&i.DriverLicenseType,
		&i.DriverLicenseIssueDate,
		&i.DriverLicenseExpiry,
		&i.DriverLicenseImageUrlFront,
		&i.DriverLicenseImageUrlBack,
		&i.DrivingDisabledDate,
		&i.DrivingDisabledReason,
		&i.Nationality,
		&i.VisaType,
		&i.VisaExpiry,
		&i.RoleID,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeName,
		&i.RoleName,
	)
	return i, err
}

const getLicenseExpiringSoon = `-- name: GetLicenseExpiringSoon :many
SELECT 
    e.id, e.employee_code, e.employee_image_url, e.employee_photo_date, e.last_name, e.first_name, e.last_name_kana, e.first_name_kana, e.legal_name, e.gender, e.birth_date, e.hire_date, e.appointment_date, e.office_id, e.job_type, e.employment_type, e.department, e.position, e.retirement_date, e.retirement_reason, e.death_date, e.death_reason, e.driver_license_no, e.driver_license_type, e.driver_license_issue_date, e.driver_license_expiry, e.driver_license_image_url_front, e.driver_license_image_url_back, e.driving_disabled_date, e.driving_disabled_reason, e.nationality, e.visa_type, e.visa_expiry, e.role_id, e.password_hash, e.password_updated_at, e.failed_login_attempts, e.locked_until, e.last_login_at, e.is_active, e.created_at, e.updated_at, e.deleted_at,
    o.office_name
FROM employees e
LEFT JOIN company_offices o ON e.office_id = o.id
WHERE e.driver_license_expiry IS NOT NULL
AND e.driver_license_expiry BETWEEN CURRENT_DATE AND CURRENT_DATE + $1::interval
AND e.is_active = true
AND e.deleted_at IS NULL
ORDER BY e.driver_license_expiry
`

type GetLicenseExpiringSoonRow struct {
	ID                         int32              `json:"id"`
	EmployeeCode               *string            `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     *string            `json:"gender"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                *string            `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                 *string            `json:"office_name"`
}

// 免許証の有効期限が近い従業員を取得
func (q *Queries) GetLicenseExpiringSoon(ctx context.Context, dollar_1 pgtype.Interval) ([]GetLicenseExpiringSoonRow, error) {
	rows, err := q.db.Query(ctx, getLicenseExpiringSoon, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLicenseExpiringSoonRow{}
	for rows.Next() {
		var i GetLicenseExpiringSoonRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.EmployeeImageUrl,
			&i.EmployeePhotoDate,
			&i.LastName,
			&i.FirstName,
			&i.LastNameKana,
			&i.FirstNameKana,
			&i.LegalName,
			&i.Gender,
			&i.BirthDate,
			&i.HireDate,
			&i.AppointmentDate,
			&i.OfficeID,
			&i.JobType,
			&i.EmploymentType,
			&i.Department,
			&i.Position,
			&i.RetirementDate,
			&i.RetirementReason,
			&i.DeathDate,
			&i.DeathReason,
			&i.DriverLicenseNo,
			&i.DriverLicenseType,
			&i.DriverLicenseIssueDate,
			&i.DriverLicenseExpiry,
			&i.DriverLicenseImageUrlFront,
			&i.DriverLicenseImageUrlBack,
			&i.DrivingDisabledDate,
			&i.DrivingDisabledReason,
			&i.Nationality,
			&i.VisaType,
			&i.VisaExpiry,
			&i.RoleID,
			&i.PasswordHash,
			&i.PasswordUpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveEmployees = `-- name: ListActiveEmployees :many
SELECT 
    e.id, e.employee_code, e.employee_image_url, e.employee_photo_date, e.last_name, e.first_name, e.last_name_kana, e.first_name_kana, e.legal_name, e.gender, e.birth_date, e.hire_date, e.appointment_date, e.office_id, e.job_type, e.employment_type, e.department, e.position, e.retirement_date, e.retirement_reason, e.death_date, e.death_reason, e.driver_license_no, e.driver_license_type, e.driver_license_issue_date, e.driver_license_expiry, e.driver_license_image_url_front, e.driver_license_image_url_back, e.driving_disabled_date, e.driving_disabled_reason, e.nationality, e.visa_type, e.visa_expiry, e.role_id, e.password_hash, e.password_updated_at, e.failed_login_attempts, e.locked_until, e.last_login_at, e.is_active, e.created_at, e.updated_at, e.deleted_at,
    o.office_name,
    r.name as role_name
FROM employees e
LEFT JOIN company_offices o ON e.office_id = o.id
LEFT JOIN m_roles r ON e.role_id = r.id
WHERE e.is_active = true
AND e.deleted_at IS NULL
ORDER BY e.employee_code
`

type ListActiveEmployeesRow struct {
	ID                         int32              `json:"id"`
	EmployeeCode               *string            `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     *string            `json:"gender"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                *string            `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                 *string            `json:"office_name"`
	RoleName                   *string            `json:"role_name"`
}

// アクティブな従業員一覧
func (q *Queries) ListActiveEmployees(ctx context.Context) ([]ListActiveEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listActiveEmployees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEmployeesRow{}
	for rows.Next() {
		var i ListActiveEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.EmployeeImageUrl,
			&i.EmployeePhotoDate,
			&i.LastName,
			&i.FirstName,
			&i.LastNameKana,
			&i.FirstNameKana,
			&i.LegalName,
			&i.Gender,
			&i.BirthDate,
			&i.HireDate,
			&i.AppointmentDate,
			&i.OfficeID,
			&i.JobType,
			&i.EmploymentType,
			&i.Department,
			&i.Position,
			&i.RetirementDate,
			&i.RetirementReason,
			&i.DeathDate,
			&i.DeathReason,
			&i.DriverLicenseNo,
			&i.DriverLicenseType,
			&i.DriverLicenseIssueDate,
			&i.DriverLicenseExpiry,
			&i.DriverLicenseImageUrlFront,
			&i.DriverLicenseImageUrlBack,
			&i.DrivingDisabledDate,
			&i.DrivingDisabledReason,
			&i.Nationality,
			&i.VisaType,
			&i.VisaExpiry,
			&i.RoleID,
			&i.PasswordHash,
			&i.PasswordUpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDrivers = `-- name: ListDrivers :many
SELECT 
    e.id, e.employee_code, e.employee_image_url, e.employee_photo_date, e.last_name, e.first_name, e.last_name_kana, e.first_name_kana, e.legal_name, e.gender, e.birth_date, e.hire_date, e.appointment_date, e.office_id, e.job_type, e.employment_type, e.department, e.position, e.retirement_date, e.retirement_reason, e.death_date, e.death_reason, e.driver_license_no, e.driver_license_type, e.driver_license_issue_date, e.driver_license_expiry, e.driver_license_image_url_front, e.driver_license_image_url_back, e.driving_disabled_date, e.driving_disabled_reason, e.nationality, e.visa_type, e.visa_expiry, e.role_id, e.password_hash, e.password_updated_at, e.failed_login_attempts, e.locked_until, e.last_login_at, e.is_active, e.created_at, e.updated_at, e.deleted_at,
    o.office_name
FROM employees e
LEFT JOIN company_offices o ON e.office_id = o.id
WHERE e.job_type = '運転者'
AND e.is_active = true
AND e.deleted_at IS NULL
AND (e.driving_disabled_date IS NULL OR e.driving_disabled_date > CURRENT_DATE)
AND (e.retirement_date IS NULL OR e.retirement_date > CURRENT_DATE)
ORDER BY e.employee_code
`

type ListDriversRow struct {
	ID                         int32              `json:"id"`
	EmployeeCode               *string            `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     *string            `json:"gender"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                *string            `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                 *string            `json:"office_name"`
}

// 運転者一覧を取得（配車用）
func (q *Queries) ListDrivers(ctx context.Context) ([]ListDriversRow, error) {
	rows, err := q.db.Query(ctx, listDrivers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDriversRow{}
	for rows.Next() {
		var i ListDriversRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.EmployeeImageUrl,
			&i.EmployeePhotoDate,
			&i.LastName,
			&i.FirstName,
			&i.LastNameKana,
			&i.FirstNameKana,
			&i.LegalName,
			&i.Gender,
			&i.BirthDate,
			&i.HireDate,
			&i.AppointmentDate,
			&i.OfficeID,
			&i.JobType,
			&i.EmploymentType,
			&i.Department,
			&i.Position,
			&i.RetirementDate,
			&i.RetirementReason,
			&i.DeathDate,
			&i.DeathReason,
			&i.DriverLicenseNo,
			&i.DriverLicenseType,
			&i.DriverLicenseIssueDate,
			&i.DriverLicenseExpiry,
			&i.DriverLicenseImageUrlFront,
			&i.DriverLicenseImageUrlBack,
			&i.DrivingDisabledDate,
			&i.DrivingDisabledReason,
			&i.Nationality,
			&i.VisaType,
			&i.VisaExpiry,
			&i.RoleID,
			&i.PasswordHash,
			&i.PasswordUpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployees = `-- name: ListEmployees :many
SELECT 
    e.id, e.employee_code, e.employee_image_url, e.employee_photo_date, e.last_name, e.first_name, e.last_name_kana, e.first_name_kana, e.legal_name, e.gender, e.birth_date, e.hire_date, e.appointment_date, e.office_id, e.job_type, e.employment_type, e.department, e.position, e.retirement_date, e.retirement_reason, e.death_date, e.death_reason, e.driver_license_no, e.driver_license_type, e.driver_license_issue_date, e.driver_license_expiry, e.driver_license_image_url_front, e.driver_license_image_url_back, e.driving_disabled_date, e.driving_disabled_reason, e.nationality, e.visa_type, e.visa_expiry, e.role_id, e.password_hash, e.password_updated_at, e.failed_login_attempts, e.locked_until, e.last_login_at, e.is_active, e.created_at, e.updated_at, e.deleted_at,
    o.office_name,
    r.name as role_name
FROM employees e
LEFT JOIN company_offices o ON e.office_id = o.id
LEFT JOIN m_roles r ON e.role_id = r.id
WHERE e.deleted_at IS NULL
ORDER BY e.employee_code
LIMIT $1 OFFSET $2
`

type ListEmployeesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListEmployeesRow struct {
	ID                         int32              `json:"id"`
	EmployeeCode               *string            `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     *string            `json:"gender"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                *string            `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                 *string            `json:"office_name"`
	RoleName                   *string            `json:"role_name"`
}

// 従業員一覧を取得
func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesRow{}
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.EmployeeImageUrl,
			&i.EmployeePhotoDate,
			&i.LastName,
			&i.FirstName,
			&i.LastNameKana,
			&i.FirstNameKana,
			&i.LegalName,
			&i.Gender,
			&i.BirthDate,
			&i.HireDate,
			&i.AppointmentDate,
			&i.OfficeID,
			&i.JobType,
			&i.EmploymentType,
			&i.Department,
			&i.Position,
			&i.RetirementDate,
			&i.RetirementReason,
			&i.DeathDate,
			&i.DeathReason,
			&i.DriverLicenseNo,
			&i.DriverLicenseType,
			&i.DriverLicenseIssueDate,
			&i.DriverLicenseExpiry,
			&i.DriverLicenseImageUrlFront,
			&i.DriverLicenseImageUrlBack,
			&i.DrivingDisabledDate,
			&i.DrivingDisabledReason,
			&i.Nationality,
			&i.VisaType,
			&i.VisaExpiry,
			&i.RoleID,
			&i.PasswordHash,
			&i.PasswordUpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeesByOffice = `-- name: ListEmployeesByOffice :many
SELECT 
    e.id, e.employee_code, e.employee_image_url, e.employee_photo_date, e.last_name, e.first_name, e.last_name_kana, e.first_name_kana, e.legal_name, e.gender, e.birth_date, e.hire_date, e.appointment_date, e.office_id, e.job_type, e.employment_type, e.department, e.position, e.retirement_date, e.retirement_reason, e.death_date, e.death_reason, e.driver_license_no, e.driver_license_type, e.driver_license_issue_date, e.driver_license_expiry, e.driver_license_image_url_front, e.driver_license_image_url_back, e.driving_disabled_date, e.driving_disabled_reason, e.nationality, e.visa_type, e.visa_expiry, e.role_id, e.password_hash, e.password_updated_at, e.failed_login_attempts, e.locked_until, e.last_login_at, e.is_active, e.created_at, e.updated_at, e.deleted_at,
    r.name as role_name
FROM employees e
LEFT JOIN m_roles r ON e.role_id = r.id
WHERE e.office_id = $1
AND e.deleted_at IS NULL
ORDER BY e.employee_code
`

type ListEmployeesByOfficeRow struct {
	ID                         int32              `json:"id"`
	EmployeeCode               *string            `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     *string            `json:"gender"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                *string            `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	RoleName                   *string            `json:"role_name"`
}

// 事業所別の従業員一覧
func (q *Queries) ListEmployeesByOffice(ctx context.Context, officeID *int32) ([]ListEmployeesByOfficeRow, error) {
	rows, err := q.db.Query(ctx, listEmployeesByOffice, officeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeesByOfficeRow{}
	for rows.Next() {
		var i ListEmployeesByOfficeRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.EmployeeImageUrl,
			&i.EmployeePhotoDate,
			&i.LastName,
			&i.FirstName,
			&i.LastNameKana,
			&i.FirstNameKana,
			&i.LegalName,
			&i.Gender,
			&i.BirthDate,
			&i.HireDate,
			&i.AppointmentDate,
			&i.OfficeID,
			&i.JobType,
			&i.EmploymentType,
			&i.Department,
			&i.Position,
			&i.RetirementDate,
			&i.RetirementReason,
			&i.DeathDate,
			&i.DeathReason,
			&i.DriverLicenseNo,
			&i.DriverLicenseType,
			&i.DriverLicenseIssueDate,
			&i.DriverLicenseExpiry,
			&i.DriverLicenseImageUrlFront,
			&i.DriverLicenseImageUrlBack,
			&i.DrivingDisabledDate,
			&i.DrivingDisabledReason,
			&i.Nationality,
			&i.VisaType,
			&i.VisaExpiry,
			&i.RoleID,
			&i.PasswordHash,
			&i.PasswordUpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEmployees = `-- name: SearchEmployees :many
SELECT 
    e.id, e.employee_code, e.employee_image_url, e.employee_photo_date, e.last_name, e.first_name, e.last_name_kana, e.first_name_kana, e.legal_name, e.gender, e.birth_date, e.hire_date, e.appointment_date, e.office_id, e.job_type, e.employment_type, e.department, e.position, e.retirement_date, e.retirement_reason, e.death_date, e.death_reason, e.driver_license_no, e.driver_license_type, e.driver_license_issue_date, e.driver_license_expiry, e.driver_license_image_url_front, e.driver_license_image_url_back, e.driving_disabled_date, e.driving_disabled_reason, e.nationality, e.visa_type, e.visa_expiry, e.role_id, e.password_hash, e.password_updated_at, e.failed_login_attempts, e.locked_until, e.last_login_at, e.is_active, e.created_at, e.updated_at, e.deleted_at,
    o.office_name,
    r.name as role_name
FROM employees e
LEFT JOIN company_offices o ON e.office_id = o.id
LEFT JOIN m_roles r ON e.role_id = r.id
WHERE e.deleted_at IS NULL
AND (
    $1::text IS NULL OR e.employee_code ILIKE '%' || $1 || '%'
    OR e.last_name ILIKE '%' || $1 || '%'
    OR e.first_name ILIKE '%' || $1 || '%'
    OR e.last_name_kana ILIKE '%' || $1 || '%'
    OR e.first_name_kana ILIKE '%' || $1 || '%'
)
AND ($2::integer IS NULL OR e.office_id = $2)
AND ($3::text IS NULL OR e.job_type = $3)
AND ($4::boolean IS NULL OR e.is_active = $4)
ORDER BY e.employee_code
LIMIT $5 OFFSET $6
`

type SearchEmployeesParams struct {
	Column1 string `json:"column_1"`
	Column2 int32  `json:"column_2"`
	Column3 string `json:"column_3"`
	Column4 bool   `json:"column_4"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchEmployeesRow struct {
	ID                         int32              `json:"id"`
	EmployeeCode               *string            `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     *string            `json:"gender"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                *string            `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                 *string            `json:"office_name"`
	RoleName                   *string            `json:"role_name"`
}

// 従業員を検索
func (q *Queries) SearchEmployees(ctx context.Context, arg SearchEmployeesParams) ([]SearchEmployeesRow, error) {
	rows, err := q.db.Query(ctx, searchEmployees,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchEmployeesRow{}
	for rows.Next() {
		var i SearchEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.EmployeeImageUrl,
			&i.EmployeePhotoDate,
			&i.LastName,
			&i.FirstName,
			&i.LastNameKana,
			&i.FirstNameKana,
			&i.LegalName,
			&i.Gender,
			&i.BirthDate,
			&i.HireDate,
			&i.AppointmentDate,
			&i.OfficeID,
			&i.JobType,
			&i.EmploymentType,
			&i.Department,
			&i.Position,
			&i.RetirementDate,
			&i.RetirementReason,
			&i.DeathDate,
			&i.DeathReason,
			&i.DriverLicenseNo,
			&i.DriverLicenseType,
			&i.DriverLicenseIssueDate,
			&i.DriverLicenseExpiry,
			&i.DriverLicenseImageUrlFront,
			&i.DriverLicenseImageUrlBack,
			&i.DrivingDisabledDate,
			&i.DrivingDisabledReason,
			&i.Nationality,
			&i.VisaType,
			&i.VisaExpiry,
			&i.RoleID,
			&i.PasswordHash,
			&i.PasswordUpdatedAt,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.LastLoginAt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setEmployeeRetirement = `-- name: SetEmployeeRetirement :exec
UPDATE employees
SET
    retirement_date = $2,
    retirement_reason = $3,
    is_active = false,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type SetEmployeeRetirementParams struct {
	ID               int32       `json:"id"`
	RetirementDate   pgtype.Date `json:"retirement_date"`
	RetirementReason *string     `json:"retirement_reason"`
}

// 従業員を退職処理
func (q *Queries) SetEmployeeRetirement(ctx context.Context, arg SetEmployeeRetirementParams) error {
	_, err := q.db.Exec(ctx, setEmployeeRetirement, arg.ID, arg.RetirementDate, arg.RetirementReason)
	return err
}

const updateEmployee = `-- name: UpdateEmployee :exec
UPDATE employees
SET
    last_name = COALESCE($1, last_name),
    first_name = COALESCE($2, first_name),
    last_name_kana = COALESCE($3, last_name_kana),
    first_name_kana = COALESCE($4, first_name_kana),
    legal_name = COALESCE($5, legal_name),
    gender = COALESCE($6, gender),
    birth_date = COALESCE($7, birth_date),
    office_id = COALESCE($8, office_id),
    job_type = COALESCE($9, job_type),
    employment_type = COALESCE($10, employment_type),
    department = COALESCE($11, department),
    position = COALESCE($12, position),
    role_id = COALESCE($13, role_id),
    is_active = COALESCE($14, is_active),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $15
`

type UpdateEmployeeParams struct {
	LastName       *string     `json:"last_name"`
	FirstName      *string     `json:"first_name"`
	LastNameKana   *string     `json:"last_name_kana"`
	FirstNameKana  *string     `json:"first_name_kana"`
	LegalName      *string     `json:"legal_name"`
	Gender         *string     `json:"gender"`
	BirthDate      pgtype.Date `json:"birth_date"`
	OfficeID       *int32      `json:"office_id"`
	JobType        *string     `json:"job_type"`
	EmploymentType *string     `json:"employment_type"`
	Department     *string     `json:"department"`
	Position       *string     `json:"position"`
	RoleID         *int32      `json:"role_id"`
	IsActive       *bool       `json:"is_active"`
	ID             int32       `json:"id"`
}

// 従業員情報を更新
func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error {
	_, err := q.db.Exec(ctx, updateEmployee,
		arg.LastName,
		arg.FirstName,
		arg.LastNameKana,
		arg.FirstNameKana,
		arg.LegalName,
		arg.Gender,
		arg.BirthDate,
		arg.OfficeID,
		arg.JobType,
		arg.EmploymentType,
		arg.Department,
		arg.Position,
		arg.RoleID,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateEmployeeLicense = `-- name: UpdateEmployeeLicense :exec
UPDATE employees
SET
    driver_license_no = $2,
    driver_license_type = $3,
    driver_license_issue_date = $4,
    driver_license_expiry = $5,
    driver_license_image_url_front = $6,
    driver_license_image_url_back = $7,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateEmployeeLicenseParams struct {
	ID                         int32       `json:"id"`
	DriverLicenseNo            *string     `json:"driver_license_no"`
	DriverLicenseType          *string     `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string     `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string     `json:"driver_license_image_url_back"`
}

// 運転免許情報を更新
func (q *Queries) UpdateEmployeeLicense(ctx context.Context, arg UpdateEmployeeLicenseParams) error {
	_, err := q.db.Exec(ctx, updateEmployeeLicense,
		arg.ID,
		arg.DriverLicenseNo,
		arg.DriverLicenseType,
		arg.DriverLicenseIssueDate,
		arg.DriverLicenseExpiry,
		arg.DriverLicenseImageUrlFront,
		arg.DriverLicenseImageUrlBack,
	)
	return err
}
