// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmployeeAccidentRecords = `-- name: GetEmployeeAccidentRecords :many
SELECT id, employee_id, accident_date, accident_type, accident_location, notes, created_at, updated_at FROM accident_records WHERE employee_id = $1
`

// 事故履歴
func (q *Queries) GetEmployeeAccidentRecords(ctx context.Context, employeeID int32) ([]AccidentRecord, error) {
	rows, err := q.db.Query(ctx, getEmployeeAccidentRecords, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccidentRecord{}
	for rows.Next() {
		var i AccidentRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.AccidentDate,
			&i.AccidentType,
			&i.AccidentLocation,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeBasicInfo = `-- name: GetEmployeeBasicInfo :one
SELECT 
e.id, e.employee_code, e.employee_image_url, e.employee_photo_date, e.last_name, e.first_name, e.last_name_kana, e.first_name_kana, e.legal_name, e.gender, e.blood_type, e.address, e.phone, e.email, e.birth_date, e.hire_date, e.appointment_date, e.office_id, e.job_type, e.employment_type, e.department, e.position, e.retirement_date, e.retirement_reason, e.death_date, e.death_reason, e.driver_license_no, e.driver_license_type, e.driver_license_issue_date, e.driver_license_expiry, e.driver_license_image_url_front, e.driver_license_image_url_back, e.driving_disabled_date, e.driving_disabled_reason, e.nationality, e.visa_type, e.visa_expiry, e.visa_image_url_front, e.visa_image_url_back, e.bank_code, e.bank_name, e.bank_branch_code, e.bank_branch_name, e.bank_account_type, e.bank_account_number, e.bank_account_name, e.bank_account_kana, e.role_id, e.password_hash, e.password_updated_at, e.failed_login_attempts, e.locked_until, e.last_login_at, e.is_active, e.created_at, e.updated_at, e.deleted_at, 
co.office_name, 
co.office_type,
r.name as role_name
FROM employees e
LEFT JOIN company_offices co ON e.office_id = co.id AND co.deleted_at IS NULL
LEFT JOIN m_roles r ON e.role_id = r.id
WHERE e.id = $1 AND e.deleted_at IS NULL
`

type GetEmployeeBasicInfoRow struct {
	ID                         int32              `json:"id"`
	EmployeeCode               string             `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     string             `json:"gender"`
	BloodType                  string             `json:"blood_type"`
	Address                    *string            `json:"address"`
	Phone                      *string            `json:"phone"`
	Email                      *string            `json:"email"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                string             `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	VisaImageUrlFront          *string            `json:"visa_image_url_front"`
	VisaImageUrlBack           *string            `json:"visa_image_url_back"`
	BankCode                   *string            `json:"bank_code"`
	BankName                   *string            `json:"bank_name"`
	BankBranchCode             *string            `json:"bank_branch_code"`
	BankBranchName             *string            `json:"bank_branch_name"`
	BankAccountType            *string            `json:"bank_account_type"`
	BankAccountNumber          *string            `json:"bank_account_number"`
	BankAccountName            *string            `json:"bank_account_name"`
	BankAccountKana            *string            `json:"bank_account_kana"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   bool               `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                 *string            `json:"office_name"`
	OfficeType                 *string            `json:"office_type"`
	RoleName                   *string            `json:"role_name"`
}

// 基本情報 + 所属事業所 + 制限情報
func (q *Queries) GetEmployeeBasicInfo(ctx context.Context, id int32) (GetEmployeeBasicInfoRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeBasicInfo, id)
	var i GetEmployeeBasicInfoRow
	err := row.Scan(
		&i.ID,
		&i.EmployeeCode,
		&i.EmployeeImageUrl,
		&i.EmployeePhotoDate,
		&i.LastName,
		&i.FirstName,
		&i.LastNameKana,
		&i.FirstNameKana,
		&i.LegalName,
		&i.Gender,
		&i.BloodType,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.BirthDate,
		&i.HireDate,
		&i.AppointmentDate,
		&i.OfficeID,
		&i.JobType,
		&i.EmploymentType,
		&i.Department,
		&i.Position,
		&i.RetirementDate,
		&i.RetirementReason,
		&i.DeathDate,
		&i.DeathReason,
		&i.DriverLicenseNo,
		&i.DriverLicenseType,
		&i.DriverLicenseIssueDate,
		&i.DriverLicenseExpiry,
		&i.DriverLicenseImageUrlFront,
		&i.DriverLicenseImageUrlBack,
		&i.DrivingDisabledDate,
		&i.DrivingDisabledReason,
		&i.Nationality,
		&i.VisaType,
		&i.VisaExpiry,
		&i.VisaImageUrlFront,
		&i.VisaImageUrlBack,
		&i.BankCode,
		&i.BankName,
		&i.BankBranchCode,
		&i.BankBranchName,
		&i.BankAccountType,
		&i.BankAccountNumber,
		&i.BankAccountName,
		&i.BankAccountKana,
		&i.RoleID,
		&i.PasswordHash,
		&i.PasswordUpdatedAt,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeName,
		&i.OfficeType,
		&i.RoleName,
	)
	return i, err
}

const getEmployeeCardList = `-- name: GetEmployeeCardList :many
SELECT 
    id, 
    employee_code, 
    employee_image_url, 
    last_name, 
    first_name,
    email,
    phone
FROM employees
WHERE deleted_at IS NULL
ORDER BY employee_code
LIMIT $1 OFFSET $2
`

type GetEmployeeCardListParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetEmployeeCardListRow struct {
	ID               int32   `json:"id"`
	EmployeeCode     string  `json:"employee_code"`
	EmployeeImageUrl *string `json:"employee_image_url"`
	LastName         string  `json:"last_name"`
	FirstName        string  `json:"first_name"`
	Email            *string `json:"email"`
	Phone            *string `json:"phone"`
}

func (q *Queries) GetEmployeeCardList(ctx context.Context, arg GetEmployeeCardListParams) ([]GetEmployeeCardListRow, error) {
	rows, err := q.db.Query(ctx, getEmployeeCardList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEmployeeCardListRow{}
	for rows.Next() {
		var i GetEmployeeCardListRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeCode,
			&i.EmployeeImageUrl,
			&i.LastName,
			&i.FirstName,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeCareerRecords = `-- name: GetEmployeeCareerRecords :many
SELECT id, employee_id, company_name, start_date, end_date, job_type, retirement_reason, created_at, updated_at FROM career_records WHERE employee_id = $1
`

// 職歴
func (q *Queries) GetEmployeeCareerRecords(ctx context.Context, employeeID int32) ([]CareerRecord, error) {
	rows, err := q.db.Query(ctx, getEmployeeCareerRecords, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CareerRecord{}
	for rows.Next() {
		var i CareerRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.CompanyName,
			&i.StartDate,
			&i.EndDate,
			&i.JobType,
			&i.RetirementReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeEducationRecords = `-- name: GetEmployeeEducationRecords :many
SELECT id, employee_id, education_type, education_date, education_institution, notes, created_at, updated_at FROM education_records WHERE employee_id = $1
`

// 学歴
func (q *Queries) GetEmployeeEducationRecords(ctx context.Context, employeeID int32) ([]EducationRecord, error) {
	rows, err := q.db.Query(ctx, getEmployeeEducationRecords, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EducationRecord{}
	for rows.Next() {
		var i EducationRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.EducationType,
			&i.EducationDate,
			&i.EducationInstitution,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeEmergencyContacts = `-- name: GetEmployeeEmergencyContacts :many
SELECT id, employee_id, contact_name, contact_relationship, contact_phone, created_at, updated_at FROM emergency_contacts WHERE employee_id = $1
`

// 緊急連絡先
func (q *Queries) GetEmployeeEmergencyContacts(ctx context.Context, employeeID int32) ([]EmergencyContact, error) {
	rows, err := q.db.Query(ctx, getEmployeeEmergencyContacts, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmergencyContact{}
	for rows.Next() {
		var i EmergencyContact
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ContactName,
			&i.ContactRelationship,
			&i.ContactPhone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeHealthCheckupRecords = `-- name: GetEmployeeHealthCheckupRecords :many
SELECT id, employee_id, checkup_date, checkup_type, overall_result, medical_institution, notes, created_at, updated_at FROM health_checkup_records WHERE employee_id = $1
`

// 健康診断
func (q *Queries) GetEmployeeHealthCheckupRecords(ctx context.Context, employeeID int32) ([]HealthCheckupRecord, error) {
	rows, err := q.db.Query(ctx, getEmployeeHealthCheckupRecords, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HealthCheckupRecord{}
	for rows.Next() {
		var i HealthCheckupRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.CheckupDate,
			&i.CheckupType,
			&i.OverallResult,
			&i.MedicalInstitution,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeInsuranceRecords = `-- name: GetEmployeeInsuranceRecords :many
SELECT id, employee_id, insurance_type, insurance_date, insurance_number, insurance_image_url, created_at, updated_at FROM insurance_records WHERE employee_id = $1
`

// 保険
func (q *Queries) GetEmployeeInsuranceRecords(ctx context.Context, employeeID int32) ([]InsuranceRecord, error) {
	rows, err := q.db.Query(ctx, getEmployeeInsuranceRecords, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InsuranceRecord{}
	for rows.Next() {
		var i InsuranceRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.InsuranceType,
			&i.InsuranceDate,
			&i.InsuranceNumber,
			&i.InsuranceImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeQualificationRecords = `-- name: GetEmployeeQualificationRecords :many
SELECT id, employee_id, qualification_type, qualification_date, qualification_number, qualification_image_url, created_at, updated_at FROM qualification_records WHERE employee_id = $1
`

// 資格
func (q *Queries) GetEmployeeQualificationRecords(ctx context.Context, employeeID int32) ([]QualificationRecord, error) {
	rows, err := q.db.Query(ctx, getEmployeeQualificationRecords, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QualificationRecord{}
	for rows.Next() {
		var i QualificationRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.QualificationType,
			&i.QualificationDate,
			&i.QualificationNumber,
			&i.QualificationImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeTrainingRecords = `-- name: GetEmployeeTrainingRecords :many
SELECT id, employee_id, training_type, training_date, training_hours, instructor, notes, created_at, updated_at FROM training_records WHERE employee_id = $1
`

// 教育訓練
func (q *Queries) GetEmployeeTrainingRecords(ctx context.Context, employeeID int32) ([]TrainingRecord, error) {
	rows, err := q.db.Query(ctx, getEmployeeTrainingRecords, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrainingRecord{}
	for rows.Next() {
		var i TrainingRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.TrainingType,
			&i.TrainingDate,
			&i.TrainingHours,
			&i.Instructor,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeViolationRecords = `-- name: GetEmployeeViolationRecords :many
SELECT id, employee_id, violation_date, violation_type, violation_location, notes, created_at, updated_at FROM violation_records WHERE employee_id = $1
`

// 違反履歴
func (q *Queries) GetEmployeeViolationRecords(ctx context.Context, employeeID int32) ([]ViolationRecord, error) {
	rows, err := q.db.Query(ctx, getEmployeeViolationRecords, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ViolationRecord{}
	for rows.Next() {
		var i ViolationRecord
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ViolationDate,
			&i.ViolationType,
			&i.ViolationLocation,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
