// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: master.sql

package db

import (
	"context"
)

const getNationalities = `-- name: GetNationalities :many
SELECT id, name FROM m_nationalities ORDER BY display_order
`

type GetNationalitiesRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) GetNationalities(ctx context.Context) ([]GetNationalitiesRow, error) {
	rows, err := q.query(ctx, q.getNationalitiesStmt, getNationalities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetNationalitiesRow{}
	for rows.Next() {
		var i GetNationalitiesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
