// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccidentRecord struct {
	ID               int32              `json:"id"`
	EmployeeID       int32              `json:"employee_id"`
	AccidentDate     pgtype.Date        `json:"accident_date"`
	AccidentType     *string            `json:"accident_type"`
	AccidentLocation *string            `json:"accident_location"`
	Notes            *string            `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CareerRecord struct {
	ID                int32              `json:"id"`
	EmployeeID        int32              `json:"employee_id"`
	CareerType        *string            `json:"career_type"`
	CareerDate        pgtype.Date        `json:"career_date"`
	CareerInstitution *string            `json:"career_institution"`
	Notes             *string            `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Company struct {
	ID                         int32              `json:"id"`
	Name                       string             `json:"name"`
	CompanyCode                *string            `json:"company_code"`
	TransportLicenseNumber     *string            `json:"transport_license_number"`
	TransportLicenseType       *string            `json:"transport_license_type"`
	TransportLicenseIssueDate  pgtype.Date        `json:"transport_license_issue_date"`
	TransportLicenseExpiryDate pgtype.Date        `json:"transport_license_expiry_date"`
	TransportLicenseImageUrl   *string            `json:"transport_license_image_url"`
	TaxID                      *string            `json:"tax_id"`
	EstablishedDate            pgtype.Date        `json:"established_date"`
	CapitalStock               *int64             `json:"capital_stock"`
	RepresentativeName         *string            `json:"representative_name"`
	RepresentativeNameKana     *string            `json:"representative_name_kana"`
	RepresentativeNameEn       *string            `json:"representative_name_en"`
	InvoiceNumber              *string            `json:"invoice_number"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
}

type CompanyOffice struct {
	ID          int32              `json:"id"`
	CompanyID   int32              `json:"company_id"`
	OfficeCode  *string            `json:"office_code"`
	OfficeName  string             `json:"office_name"`
	OfficeType  *string            `json:"office_type"`
	ManagerID   *int32             `json:"manager_id"`
	OpeningDate pgtype.Date        `json:"opening_date"`
	ClosingDate pgtype.Date        `json:"closing_date"`
	PostalCode  *string            `json:"postal_code"`
	Address     *string            `json:"address"`
	Phone       *string            `json:"phone"`
	Fax         *string            `json:"fax"`
	Email       *string            `json:"email"`
	Website     *string            `json:"website"`
	ImageUrl    *string            `json:"image_url"`
	Notes       *string            `json:"notes"`
	IsActive    *bool              `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Customer struct {
	ID            int32              `json:"id"`
	Name          string             `json:"name"`
	CustomerCode  string             `json:"customer_code"`
	CreditLimit   pgtype.Numeric     `json:"credit_limit"`
	PaymentTerms  *string            `json:"payment_terms"`
	PaymentMethod *string            `json:"payment_method"`
	ClosingDay    *int32             `json:"closing_day"`
	PaymentDueDay *int32             `json:"payment_due_day"`
	InvoiceNumber *string            `json:"invoice_number"`
	IsActive      *bool              `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type CustomerContact struct {
	ID             int32              `json:"id"`
	CustomerID     int32              `json:"customer_id"`
	ContactCode    *string            `json:"contact_code"`
	LastName       string             `json:"last_name"`
	FirstName      string             `json:"first_name"`
	LastNameKana   *string            `json:"last_name_kana"`
	FirstNameKana  *string            `json:"first_name_kana"`
	Department     *string            `json:"department"`
	Position       *string            `json:"position"`
	OfficeLocation *string            `json:"office_location"`
	Email          *string            `json:"email"`
	PhoneDirect    *string            `json:"phone_direct"`
	PhoneMobile    *string            `json:"phone_mobile"`
	PhoneExtension *string            `json:"phone_extension"`
	IsPrimary      *bool              `json:"is_primary"`
	IsActive       *bool              `json:"is_active"`
	Notes          *string            `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryAssignment struct {
	ID                 int32              `json:"id"`
	OrderID            int32              `json:"order_id"`
	DetailID           *int32             `json:"detail_id"`
	DriverID           *int32             `json:"driver_id"`
	DriverCompanionID  *int32             `json:"driver_companion_id"`
	VehicleID          *int32             `json:"vehicle_id"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	AssignmentStatus   *string            `json:"assignment_status"`
	CancellationReason *string            `json:"cancellation_reason"`
	Notes              *string            `json:"notes"`
	AssignedBy         *int32             `json:"assigned_by"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryCharge struct {
	ID              int32              `json:"id"`
	OrderID         int32              `json:"order_id"`
	DetailID        *int32             `json:"detail_id"`
	ChargeType      *string            `json:"charge_type"`
	ChargeName      string             `json:"charge_name"`
	Amount          pgtype.Numeric     `json:"amount"`
	TaxCategory     *string            `json:"tax_category"`
	Notes           *string            `json:"notes"`
	ReceiptImageUrl *string            `json:"receipt_image_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryDetail struct {
	ID                int32              `json:"id"`
	OrderID           int32              `json:"order_id"`
	LineNumber        int32              `json:"line_number"`
	RouteFrom         *string            `json:"route_from"`
	RouteTo           *string            `json:"route_to"`
	DriverID          *int32             `json:"driver_id"`
	DriverCompanionID *int32             `json:"driver_companion_id"`
	VehicleID         *int32             `json:"vehicle_id"`
	TrailerID         *int32             `json:"trailer_id"`
	DepartureTime     pgtype.Time        `json:"departure_time"`
	ArrivalTime       pgtype.Time        `json:"arrival_time"`
	ServiceItemID     *int32             `json:"service_item_id"`
	ItemName          *string            `json:"item_name"`
	Quantity          pgtype.Numeric     `json:"quantity"`
	Unit              *string            `json:"unit"`
	UnitPrice         pgtype.Numeric     `json:"unit_price"`
	Amount            pgtype.Numeric     `json:"amount"`
	TaxCategory       *string            `json:"tax_category"`
	DetailNotes       *string            `json:"detail_notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DeliveryOrder struct {
	ID                 int32              `json:"id"`
	OrderNumber        string             `json:"order_number"`
	CustomerID         int32              `json:"customer_id"`
	ServiceType        string             `json:"service_type"`
	ServiceTypeID      *int32             `json:"service_type_id"`
	OrderDate          pgtype.Date        `json:"order_date"`
	OperationDate      pgtype.Date        `json:"operation_date"`
	DeliveryDate       pgtype.Date        `json:"delivery_date"`
	DriverID           *int32             `json:"driver_id"`
	DriverCompanionID  *int32             `json:"driver_companion_id"`
	VehicleID          *int32             `json:"vehicle_id"`
	DepartureTime      pgtype.Time        `json:"departure_time"`
	ArrivalTime        pgtype.Time        `json:"arrival_time"`
	HasHighwayFee      *bool              `json:"has_highway_fee"`
	HasExtraCharge     *bool              `json:"has_extra_charge"`
	IsTaxExempt        *bool              `json:"is_tax_exempt"`
	OrderStatus        *string            `json:"order_status"`
	BillingConfirmed   *bool              `json:"billing_confirmed"`
	BillingConfirmedBy *int32             `json:"billing_confirmed_by"`
	BillingConfirmedAt pgtype.Timestamptz `json:"billing_confirmed_at"`
	RevenueDate        pgtype.Date        `json:"revenue_date"`
	RevenueMonth       *string            `json:"revenue_month"`
	RevenueLocked      *bool              `json:"revenue_locked"`
	SubtotalAmount     pgtype.Numeric     `json:"subtotal_amount"`
	TaxAmount          pgtype.Numeric     `json:"tax_amount"`
	TotalAmount        pgtype.Numeric     `json:"total_amount"`
	InvoiceIssued      *bool              `json:"invoice_issued"`
	InvoiceNumber      *string            `json:"invoice_number"`
	InvoiceDate        pgtype.Date        `json:"invoice_date"`
	Notes              *string            `json:"notes"`
	CreatedBy          *int32             `json:"created_by"`
	AssignedTo         *int32             `json:"assigned_to"`
	IsActive           *bool              `json:"is_active"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type EducationRecord struct {
	ID                   int32              `json:"id"`
	EmployeeID           int32              `json:"employee_id"`
	EducationType        *string            `json:"education_type"`
	EducationDate        pgtype.Date        `json:"education_date"`
	EducationInstitution *string            `json:"education_institution"`
	Notes                *string            `json:"notes"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Employee struct {
	ID                         int32              `json:"id"`
	EmployeeCode               *string            `json:"employee_code"`
	EmployeeImageUrl           *string            `json:"employee_image_url"`
	EmployeePhotoDate          pgtype.Date        `json:"employee_photo_date"`
	LastName                   string             `json:"last_name"`
	FirstName                  string             `json:"first_name"`
	LastNameKana               *string            `json:"last_name_kana"`
	FirstNameKana              *string            `json:"first_name_kana"`
	LegalName                  *string            `json:"legal_name"`
	Gender                     *string            `json:"gender"`
	BirthDate                  pgtype.Date        `json:"birth_date"`
	HireDate                   pgtype.Date        `json:"hire_date"`
	AppointmentDate            pgtype.Date        `json:"appointment_date"`
	OfficeID                   *int32             `json:"office_id"`
	JobType                    *string            `json:"job_type"`
	EmploymentType             *string            `json:"employment_type"`
	Department                 *string            `json:"department"`
	Position                   *string            `json:"position"`
	RetirementDate             pgtype.Date        `json:"retirement_date"`
	RetirementReason           *string            `json:"retirement_reason"`
	DeathDate                  pgtype.Date        `json:"death_date"`
	DeathReason                *string            `json:"death_reason"`
	DriverLicenseNo            *string            `json:"driver_license_no"`
	DriverLicenseType          *string            `json:"driver_license_type"`
	DriverLicenseIssueDate     pgtype.Date        `json:"driver_license_issue_date"`
	DriverLicenseExpiry        pgtype.Date        `json:"driver_license_expiry"`
	DriverLicenseImageUrlFront *string            `json:"driver_license_image_url_front"`
	DriverLicenseImageUrlBack  *string            `json:"driver_license_image_url_back"`
	DrivingDisabledDate        pgtype.Date        `json:"driving_disabled_date"`
	DrivingDisabledReason      *string            `json:"driving_disabled_reason"`
	Nationality                *string            `json:"nationality"`
	VisaType                   *string            `json:"visa_type"`
	VisaExpiry                 pgtype.Date        `json:"visa_expiry"`
	RoleID                     *int32             `json:"role_id"`
	PasswordHash               *string            `json:"password_hash"`
	PasswordUpdatedAt          pgtype.Timestamptz `json:"password_updated_at"`
	FailedLoginAttempts        *int32             `json:"failed_login_attempts"`
	LockedUntil                pgtype.Timestamptz `json:"locked_until"`
	LastLoginAt                pgtype.Timestamptz `json:"last_login_at"`
	IsActive                   *bool              `json:"is_active"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                  pgtype.Timestamptz `json:"deleted_at"`
}

type HealthCheckupRecord struct {
	ID                 int32              `json:"id"`
	EmployeeID         int32              `json:"employee_id"`
	CheckupDate        pgtype.Date        `json:"checkup_date"`
	CheckupType        *string            `json:"checkup_type"`
	OverallResult      *string            `json:"overall_result"`
	MedicalInstitution *string            `json:"medical_institution"`
	Notes              *string            `json:"notes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type InsuranceRecord struct {
	ID                int32              `json:"id"`
	EmployeeID        int32              `json:"employee_id"`
	InsuranceType     *string            `json:"insurance_type"`
	InsuranceDate     pgtype.Date        `json:"insurance_date"`
	InsuranceImageUrl *string            `json:"insurance_image_url"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Invoice struct {
	ID                int32              `json:"id"`
	InvoiceNumber     string             `json:"invoice_number"`
	CustomerID        int32              `json:"customer_id"`
	BillingPeriodFrom pgtype.Date        `json:"billing_period_from"`
	BillingPeriodTo   pgtype.Date        `json:"billing_period_to"`
	ClosingDate       pgtype.Date        `json:"closing_date"`
	SubtotalAmount    pgtype.Numeric     `json:"subtotal_amount"`
	TaxAmount         pgtype.Numeric     `json:"tax_amount"`
	TotalAmount       pgtype.Numeric     `json:"total_amount"`
	InvoiceDate       pgtype.Date        `json:"invoice_date"`
	IssuedAt          pgtype.Timestamptz `json:"issued_at"`
	IssuedBy          *int32             `json:"issued_by"`
	PaymentDueDate    pgtype.Date        `json:"payment_due_date"`
	PaymentStatus     *string            `json:"payment_status"`
	PaymentDate       pgtype.Date        `json:"payment_date"`
	PaymentAmount     pgtype.Numeric     `json:"payment_amount"`
	Notes             *string            `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type InvoiceOrder struct {
	InvoiceID int32              `json:"invoice_id"`
	OrderID   int32              `json:"order_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LoginLog struct {
	ID            int32              `json:"id"`
	EmployeeID    *int32             `json:"employee_id"`
	EmployeeCode  *string            `json:"employee_code"`
	LoginSuccess  bool               `json:"login_success"`
	FailureReason *string            `json:"failure_reason"`
	IpAddress     *string            `json:"ip_address"`
	UserAgent     *string            `json:"user_agent"`
	AttemptedAt   pgtype.Timestamptz `json:"attempted_at"`
}

type MAddress struct {
	ID            int32              `json:"id"`
	OwnerType     string             `json:"owner_type"`
	OwnerID       int32              `json:"owner_id"`
	PostalCode    *string            `json:"postal_code"`
	Prefecture    *string            `json:"prefecture"`
	City          *string            `json:"city"`
	StreetAddress *string            `json:"street_address"`
	BuildingName  *string            `json:"building_name"`
	IsPrimary     *bool              `json:"is_primary"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MBank struct {
	ID            int32              `json:"id"`
	OwnerType     string             `json:"owner_type"`
	OwnerID       int32              `json:"owner_id"`
	BankCode      string             `json:"bank_code"`
	BankName      string             `json:"bank_name"`
	BranchCode    *string            `json:"branch_code"`
	BranchName    *string            `json:"branch_name"`
	AccountType   int16              `json:"account_type"`
	AccountNumber string             `json:"account_number"`
	AccountName   string             `json:"account_name"`
	AccountKana   *string            `json:"account_kana"`
	IsActive      *bool              `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type MEmail struct {
	ID        int32              `json:"id"`
	OwnerType string             `json:"owner_type"`
	OwnerID   int32              `json:"owner_id"`
	Email     string             `json:"email"`
	IsPrimary *bool              `json:"is_primary"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type MPhone struct {
	ID          int32              `json:"id"`
	OwnerType   string             `json:"owner_type"`
	OwnerID     int32              `json:"owner_id"`
	PhoneNumber string             `json:"phone_number"`
	PhoneType   int16              `json:"phone_type"`
	IsPrimary   *bool              `json:"is_primary"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type MRole struct {
	ID        int32              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type QualificationRecord struct {
	ID                    int32              `json:"id"`
	EmployeeID            int32              `json:"employee_id"`
	QualificationType     *string            `json:"qualification_type"`
	QualificationDate     pgtype.Date        `json:"qualification_date"`
	QualificationNumber   *string            `json:"qualification_number"`
	QualificationImageUrl *string            `json:"qualification_image_url"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type ServiceItem struct {
	ID          int32              `json:"id"`
	ServiceType *string            `json:"service_type"`
	ItemName    string             `json:"item_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Session struct {
	ID             int32              `json:"id"`
	EmployeeID     int32              `json:"employee_id"`
	SessionToken   string             `json:"session_token"`
	IpAddress      *string            `json:"ip_address"`
	UserAgent      *string            `json:"user_agent"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastAccessedAt pgtype.Timestamptz `json:"last_accessed_at"`
}

type TrainingRecord struct {
	ID            int32              `json:"id"`
	EmployeeID    int32              `json:"employee_id"`
	TrainingType  string             `json:"training_type"`
	TrainingDate  pgtype.Date        `json:"training_date"`
	TrainingHours pgtype.Numeric     `json:"training_hours"`
	Instructor    *string            `json:"instructor"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Vehicle struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
}

type VehicleAccidentRecord struct {
	ID                       int32              `json:"id"`
	VehicleID                int32              `json:"vehicle_id"`
	DriverID                 *int32             `json:"driver_id"`
	AccidentDate             pgtype.Date        `json:"accident_date"`
	AccidentTime             pgtype.Time        `json:"accident_time"`
	AccidentLocation         *string            `json:"accident_location"`
	AccidentType             *string            `json:"accident_type"`
	AccidentSeverity         *string            `json:"accident_severity"`
	Description              *string            `json:"description"`
	WeatherCondition         *string            `json:"weather_condition"`
	RoadCondition            *string            `json:"road_condition"`
	OtherPartyName           *string            `json:"other_party_name"`
	OtherPartyPhone          *string            `json:"other_party_phone"`
	OtherPartyInsurance      *string            `json:"other_party_insurance"`
	PoliceReported           *bool              `json:"police_reported"`
	PoliceReportNumber       *string            `json:"police_report_number"`
	InsuranceClaimNumber     *string            `json:"insurance_claim_number"`
	VehicleDamageDescription *string            `json:"vehicle_damage_description"`
	RepairCost               pgtype.Numeric     `json:"repair_cost"`
	RepairShop               *string            `json:"repair_shop"`
	RepairStartDate          pgtype.Date        `json:"repair_start_date"`
	RepairEndDate            pgtype.Date        `json:"repair_end_date"`
	AccidentImageUrl         *string            `json:"accident_image_url"`
	PoliceReportImageUrl     *string            `json:"police_report_image_url"`
	Notes                    *string            `json:"notes"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
}

type VehicleDailyInspection struct {
	ID                     int32              `json:"id"`
	VehicleID              int32              `json:"vehicle_id"`
	DriverID               int32              `json:"driver_id"`
	InspectionDate         pgtype.Date        `json:"inspection_date"`
	InspectionTime         pgtype.Time        `json:"inspection_time"`
	InspectionType         *string            `json:"inspection_type"`
	OdometerReading        *int32             `json:"odometer_reading"`
	EngineOilLevel         *string            `json:"engine_oil_level"`
	CoolantLevel           *string            `json:"coolant_level"`
	BrakeFluidLevel        *string            `json:"brake_fluid_level"`
	WasherFluidLevel       *string            `json:"washer_fluid_level"`
	BatteryCondition       *string            `json:"battery_condition"`
	EngineNoise            *string            `json:"engine_noise"`
	TirePressureFl         *string            `json:"tire_pressure_fl"`
	TirePressureFr         *string            `json:"tire_pressure_fr"`
	TirePressureRl         *string            `json:"tire_pressure_rl"`
	TirePressureRr         *string            `json:"tire_pressure_rr"`
	TireTreadDepth         *string            `json:"tire_tread_depth"`
	TireDamage             *string            `json:"tire_damage"`
	WheelNuts              *string            `json:"wheel_nuts"`
	Headlights             *string            `json:"headlights"`
	TailLights             *string            `json:"tail_lights"`
	BrakeLights            *string            `json:"brake_lights"`
	TurnSignals            *string            `json:"turn_signals"`
	HazardLights           *string            `json:"hazard_lights"`
	ClearanceLights        *string            `json:"clearance_lights"`
	FootBrakeOperation     *string            `json:"foot_brake_operation"`
	ParkingBrakeOperation  *string            `json:"parking_brake_operation"`
	BrakeEffectiveness     *string            `json:"brake_effectiveness"`
	AirBrakePressure       *string            `json:"air_brake_pressure"`
	SteeringOperation      *string            `json:"steering_operation"`
	SteeringPlay           *string            `json:"steering_play"`
	ClutchOperation        *string            `json:"clutch_operation"`
	AcceleratorOperation   *string            `json:"accelerator_operation"`
	GearShiftOperation     *string            `json:"gear_shift_operation"`
	WindshieldWipers       *string            `json:"windshield_wipers"`
	Horn                   *string            `json:"horn"`
	Mirrors                *string            `json:"mirrors"`
	WindowsWindshield      *string            `json:"windows_windshield"`
	SeatBelt               *string            `json:"seat_belt"`
	Speedometer            *string            `json:"speedometer"`
	CargoBedCondition      *string            `json:"cargo_bed_condition"`
	LoadingPlatform        *string            `json:"loading_platform"`
	TailgateOperation      *string            `json:"tailgate_operation"`
	BodyDamage             *string            `json:"body_damage"`
	FuelLeak               *string            `json:"fuel_leak"`
	OilLeak                *string            `json:"oil_leak"`
	WaterLeak              *string            `json:"water_leak"`
	OverallStatus          string             `json:"overall_status"`
	AbnormalityFound       *bool              `json:"abnormality_found"`
	AbnormalityDescription *string            `json:"abnormality_description"`
	ActionTaken            *string            `json:"action_taken"`
	RepairRequired         *bool              `json:"repair_required"`
	RepairScheduledDate    pgtype.Date        `json:"repair_scheduled_date"`
	WeatherCondition       *string            `json:"weather_condition"`
	Temperature            pgtype.Numeric     `json:"temperature"`
	Notes                  *string            `json:"notes"`
	ConfirmedBy            *int32             `json:"confirmed_by"`
	ConfirmedAt            pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type VehicleFuelRecord struct {
	ID               int32              `json:"id"`
	VehicleID        int32              `json:"vehicle_id"`
	DriverID         *int32             `json:"driver_id"`
	FuelDate         pgtype.Date        `json:"fuel_date"`
	FuelStation      *string            `json:"fuel_station"`
	FuelType         *string            `json:"fuel_type"`
	FuelAmount       pgtype.Numeric     `json:"fuel_amount"`
	FuelUnitPrice    pgtype.Numeric     `json:"fuel_unit_price"`
	FuelTotalPrice   pgtype.Numeric     `json:"fuel_total_price"`
	OdometerReading  *int32             `json:"odometer_reading"`
	DistanceTraveled *int32             `json:"distance_traveled"`
	FuelEfficiency   pgtype.Numeric     `json:"fuel_efficiency"`
	PaymentMethod    *string            `json:"payment_method"`
	ReceiptImageUrl  *string            `json:"receipt_image_url"`
	Notes            *string            `json:"notes"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type VehicleMaintenanceRecord struct {
	ID                  int32              `json:"id"`
	VehicleID           int32              `json:"vehicle_id"`
	MaintenanceDate     pgtype.Date        `json:"maintenance_date"`
	MaintenanceType     *string            `json:"maintenance_type"`
	MaintenanceShop     *string            `json:"maintenance_shop"`
	MechanicName        *string            `json:"mechanic_name"`
	Description         *string            `json:"description"`
	PartsReplaced       *string            `json:"parts_replaced"`
	LaborCost           pgtype.Numeric     `json:"labor_cost"`
	PartsCost           pgtype.Numeric     `json:"parts_cost"`
	OtherCost           pgtype.Numeric     `json:"other_cost"`
	TotalCost           pgtype.Numeric     `json:"total_cost"`
	OdometerReading     *int32             `json:"odometer_reading"`
	NextMaintenanceDate pgtype.Date        `json:"next_maintenance_date"`
	Notes               *string            `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ViolationRecord struct {
	ID                int32              `json:"id"`
	EmployeeID        int32              `json:"employee_id"`
	ViolationDate     pgtype.Date        `json:"violation_date"`
	ViolationType     *string            `json:"violation_type"`
	ViolationLocation *string            `json:"violation_location"`
	Notes             *string            `json:"notes"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
