// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVehicles = `-- name: CountVehicles :one
SELECT COUNT(*) as count
FROM vehicles
WHERE deleted_at IS NULL
AND ($1::boolean IS NULL OR is_active = $1)
`

// 車両数をカウント
func (q *Queries) CountVehicles(ctx context.Context, dollar_1 bool) (int64, error) {
	row := q.db.QueryRow(ctx, countVehicles, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVehicle = `-- name: CreateVehicle :one

INSERT INTO vehicles (
    vehicle_code,
    vehicle_number,
    vehicle_name,
    vehicle_type,
    manufacturer,
    model_name,
    model_year,
    initial_registration_date,
    vehicle_inspection_expiry,
    max_load_capacity,
    fuel_type,
    office_id,
    is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
) RETURNING id, vehicle_code, vehicle_number, registration_number, vehicle_name, manufacturer, model_name, model_year, vehicle_type, body_type, max_load_capacity, vehicle_weight, gross_vehicle_weight, fuel_type, transmission_type, company_id, office_id, primary_driver_id, ownership_type, lease_company, lease_start_date, lease_end_date, purchase_date, purchase_price, initial_registration_date, vehicle_inspection_expiry, vehicle_inspection_certificate_image_url, compulsory_insurance_number, compulsory_insurance_expiry, compulsory_insurance_image_url, voluntary_insurance_company, voluntary_insurance_number, voluntary_insurance_expiry, voluntary_insurance_image_url, vehicle_status, odometer, last_maintenance_date, next_maintenance_date, vehicle_image_url, notes, is_active, created_at, updated_at, deleted_at
`

type CreateVehicleParams struct {
	VehicleCode             string         `json:"vehicle_code"`
	VehicleNumber           string         `json:"vehicle_number"`
	VehicleName             *string        `json:"vehicle_name"`
	VehicleType             *string        `json:"vehicle_type"`
	Manufacturer            *string        `json:"manufacturer"`
	ModelName               *string        `json:"model_name"`
	ModelYear               *int32         `json:"model_year"`
	InitialRegistrationDate pgtype.Date    `json:"initial_registration_date"`
	VehicleInspectionExpiry pgtype.Date    `json:"vehicle_inspection_expiry"`
	MaxLoadCapacity         pgtype.Numeric `json:"max_load_capacity"`
	FuelType                *string        `json:"fuel_type"`
	OfficeID                *int32         `json:"office_id"`
	IsActive                *bool          `json:"is_active"`
}

// ==============================
// 車両管理クエリ
// ==============================
// 車両を新規登録
func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.VehicleCode,
		arg.VehicleNumber,
		arg.VehicleName,
		arg.VehicleType,
		arg.Manufacturer,
		arg.ModelName,
		arg.ModelYear,
		arg.InitialRegistrationDate,
		arg.VehicleInspectionExpiry,
		arg.MaxLoadCapacity,
		arg.FuelType,
		arg.OfficeID,
		arg.IsActive,
	)
	var i Vehicle
	err := row.Scan(
		&i.ID,
		&i.VehicleCode,
		&i.VehicleNumber,
		&i.RegistrationNumber,
		&i.VehicleName,
		&i.Manufacturer,
		&i.ModelName,
		&i.ModelYear,
		&i.VehicleType,
		&i.BodyType,
		&i.MaxLoadCapacity,
		&i.VehicleWeight,
		&i.GrossVehicleWeight,
		&i.FuelType,
		&i.TransmissionType,
		&i.CompanyID,
		&i.OfficeID,
		&i.PrimaryDriverID,
		&i.OwnershipType,
		&i.LeaseCompany,
		&i.LeaseStartDate,
		&i.LeaseEndDate,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.InitialRegistrationDate,
		&i.VehicleInspectionExpiry,
		&i.VehicleInspectionCertificateImageUrl,
		&i.CompulsoryInsuranceNumber,
		&i.CompulsoryInsuranceExpiry,
		&i.CompulsoryInsuranceImageUrl,
		&i.VoluntaryInsuranceCompany,
		&i.VoluntaryInsuranceNumber,
		&i.VoluntaryInsuranceExpiry,
		&i.VoluntaryInsuranceImageUrl,
		&i.VehicleStatus,
		&i.Odometer,
		&i.LastMaintenanceDate,
		&i.NextMaintenanceDate,
		&i.VehicleImageUrl,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createVehicleFuelRecord = `-- name: CreateVehicleFuelRecord :one
INSERT INTO vehicle_fuel_records (
    vehicle_id,
    fuel_date,
    fuel_station,
    fuel_type,
    fuel_amount,
    fuel_unit_price,
    fuel_total_price,
    odometer_reading,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, vehicle_id, driver_id, fuel_date, fuel_station, fuel_type, fuel_amount, fuel_unit_price, fuel_total_price, odometer_reading, distance_traveled, fuel_efficiency, payment_method, receipt_image_url, notes, created_at
`

type CreateVehicleFuelRecordParams struct {
	VehicleID       int32          `json:"vehicle_id"`
	FuelDate        pgtype.Date    `json:"fuel_date"`
	FuelStation     *string        `json:"fuel_station"`
	FuelType        *string        `json:"fuel_type"`
	FuelAmount      pgtype.Numeric `json:"fuel_amount"`
	FuelUnitPrice   pgtype.Numeric `json:"fuel_unit_price"`
	FuelTotalPrice  pgtype.Numeric `json:"fuel_total_price"`
	OdometerReading *int32         `json:"odometer_reading"`
	Notes           *string        `json:"notes"`
}

// 燃料記録を登録
func (q *Queries) CreateVehicleFuelRecord(ctx context.Context, arg CreateVehicleFuelRecordParams) (VehicleFuelRecord, error) {
	row := q.db.QueryRow(ctx, createVehicleFuelRecord,
		arg.VehicleID,
		arg.FuelDate,
		arg.FuelStation,
		arg.FuelType,
		arg.FuelAmount,
		arg.FuelUnitPrice,
		arg.FuelTotalPrice,
		arg.OdometerReading,
		arg.Notes,
	)
	var i VehicleFuelRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.DriverID,
		&i.FuelDate,
		&i.FuelStation,
		&i.FuelType,
		&i.FuelAmount,
		&i.FuelUnitPrice,
		&i.FuelTotalPrice,
		&i.OdometerReading,
		&i.DistanceTraveled,
		&i.FuelEfficiency,
		&i.PaymentMethod,
		&i.ReceiptImageUrl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createVehicleMaintenance = `-- name: CreateVehicleMaintenance :one
INSERT INTO vehicle_maintenance_records (
    vehicle_id,
    maintenance_type,
    maintenance_date,
    odometer_reading,
    maintenance_shop,
    total_cost,
    next_maintenance_date,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, vehicle_id, maintenance_date, maintenance_type, maintenance_shop, mechanic_name, description, parts_replaced, labor_cost, parts_cost, other_cost, total_cost, odometer_reading, next_maintenance_date, notes, created_at
`

type CreateVehicleMaintenanceParams struct {
	VehicleID           int32          `json:"vehicle_id"`
	MaintenanceType     *string        `json:"maintenance_type"`
	MaintenanceDate     pgtype.Date    `json:"maintenance_date"`
	OdometerReading     *int32         `json:"odometer_reading"`
	MaintenanceShop     *string        `json:"maintenance_shop"`
	TotalCost           pgtype.Numeric `json:"total_cost"`
	NextMaintenanceDate pgtype.Date    `json:"next_maintenance_date"`
	Notes               *string        `json:"notes"`
}

// 整備記録を登録
func (q *Queries) CreateVehicleMaintenance(ctx context.Context, arg CreateVehicleMaintenanceParams) (VehicleMaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, createVehicleMaintenance,
		arg.VehicleID,
		arg.MaintenanceType,
		arg.MaintenanceDate,
		arg.OdometerReading,
		arg.MaintenanceShop,
		arg.TotalCost,
		arg.NextMaintenanceDate,
		arg.Notes,
	)
	var i VehicleMaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MaintenanceDate,
		&i.MaintenanceType,
		&i.MaintenanceShop,
		&i.MechanicName,
		&i.Description,
		&i.PartsReplaced,
		&i.LaborCost,
		&i.PartsCost,
		&i.OtherCost,
		&i.TotalCost,
		&i.OdometerReading,
		&i.NextMaintenanceDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteVehicle = `-- name: DeleteVehicle :exec
UPDATE vehicles
SET
    deleted_at = CURRENT_TIMESTAMP,
    is_active = false
WHERE id = $1
`

// 車両を論理削除
func (q *Queries) DeleteVehicle(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteVehicle, id)
	return err
}

const getVehicle = `-- name: GetVehicle :one
SELECT 
    v.id, v.vehicle_code, v.vehicle_number, v.registration_number, v.vehicle_name, v.manufacturer, v.model_name, v.model_year, v.vehicle_type, v.body_type, v.max_load_capacity, v.vehicle_weight, v.gross_vehicle_weight, v.fuel_type, v.transmission_type, v.company_id, v.office_id, v.primary_driver_id, v.ownership_type, v.lease_company, v.lease_start_date, v.lease_end_date, v.purchase_date, v.purchase_price, v.initial_registration_date, v.vehicle_inspection_expiry, v.vehicle_inspection_certificate_image_url, v.compulsory_insurance_number, v.compulsory_insurance_expiry, v.compulsory_insurance_image_url, v.voluntary_insurance_company, v.voluntary_insurance_number, v.voluntary_insurance_expiry, v.voluntary_insurance_image_url, v.vehicle_status, v.odometer, v.last_maintenance_date, v.next_maintenance_date, v.vehicle_image_url, v.notes, v.is_active, v.created_at, v.updated_at, v.deleted_at,
    o.office_name
FROM vehicles v
LEFT JOIN company_offices o ON v.office_id = o.id
WHERE v.id = $1
AND v.deleted_at IS NULL
`

type GetVehicleRow struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                           *string            `json:"office_name"`
}

// 車両をIDで取得
func (q *Queries) GetVehicle(ctx context.Context, id int32) (GetVehicleRow, error) {
	row := q.db.QueryRow(ctx, getVehicle, id)
	var i GetVehicleRow
	err := row.Scan(
		&i.ID,
		&i.VehicleCode,
		&i.VehicleNumber,
		&i.RegistrationNumber,
		&i.VehicleName,
		&i.Manufacturer,
		&i.ModelName,
		&i.ModelYear,
		&i.VehicleType,
		&i.BodyType,
		&i.MaxLoadCapacity,
		&i.VehicleWeight,
		&i.GrossVehicleWeight,
		&i.FuelType,
		&i.TransmissionType,
		&i.CompanyID,
		&i.OfficeID,
		&i.PrimaryDriverID,
		&i.OwnershipType,
		&i.LeaseCompany,
		&i.LeaseStartDate,
		&i.LeaseEndDate,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.InitialRegistrationDate,
		&i.VehicleInspectionExpiry,
		&i.VehicleInspectionCertificateImageUrl,
		&i.CompulsoryInsuranceNumber,
		&i.CompulsoryInsuranceExpiry,
		&i.CompulsoryInsuranceImageUrl,
		&i.VoluntaryInsuranceCompany,
		&i.VoluntaryInsuranceNumber,
		&i.VoluntaryInsuranceExpiry,
		&i.VoluntaryInsuranceImageUrl,
		&i.VehicleStatus,
		&i.Odometer,
		&i.LastMaintenanceDate,
		&i.NextMaintenanceDate,
		&i.VehicleImageUrl,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeName,
	)
	return i, err
}

const getVehicleByNumber = `-- name: GetVehicleByNumber :one
SELECT 
    v.id, v.vehicle_code, v.vehicle_number, v.registration_number, v.vehicle_name, v.manufacturer, v.model_name, v.model_year, v.vehicle_type, v.body_type, v.max_load_capacity, v.vehicle_weight, v.gross_vehicle_weight, v.fuel_type, v.transmission_type, v.company_id, v.office_id, v.primary_driver_id, v.ownership_type, v.lease_company, v.lease_start_date, v.lease_end_date, v.purchase_date, v.purchase_price, v.initial_registration_date, v.vehicle_inspection_expiry, v.vehicle_inspection_certificate_image_url, v.compulsory_insurance_number, v.compulsory_insurance_expiry, v.compulsory_insurance_image_url, v.voluntary_insurance_company, v.voluntary_insurance_number, v.voluntary_insurance_expiry, v.voluntary_insurance_image_url, v.vehicle_status, v.odometer, v.last_maintenance_date, v.next_maintenance_date, v.vehicle_image_url, v.notes, v.is_active, v.created_at, v.updated_at, v.deleted_at,
    o.office_name
FROM vehicles v
LEFT JOIN company_offices o ON v.office_id = o.id
WHERE v.vehicle_number = $1
AND v.deleted_at IS NULL
`

type GetVehicleByNumberRow struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                           *string            `json:"office_name"`
}

// 車両番号で取得
func (q *Queries) GetVehicleByNumber(ctx context.Context, vehicleNumber string) (GetVehicleByNumberRow, error) {
	row := q.db.QueryRow(ctx, getVehicleByNumber, vehicleNumber)
	var i GetVehicleByNumberRow
	err := row.Scan(
		&i.ID,
		&i.VehicleCode,
		&i.VehicleNumber,
		&i.RegistrationNumber,
		&i.VehicleName,
		&i.Manufacturer,
		&i.ModelName,
		&i.ModelYear,
		&i.VehicleType,
		&i.BodyType,
		&i.MaxLoadCapacity,
		&i.VehicleWeight,
		&i.GrossVehicleWeight,
		&i.FuelType,
		&i.TransmissionType,
		&i.CompanyID,
		&i.OfficeID,
		&i.PrimaryDriverID,
		&i.OwnershipType,
		&i.LeaseCompany,
		&i.LeaseStartDate,
		&i.LeaseEndDate,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.InitialRegistrationDate,
		&i.VehicleInspectionExpiry,
		&i.VehicleInspectionCertificateImageUrl,
		&i.CompulsoryInsuranceNumber,
		&i.CompulsoryInsuranceExpiry,
		&i.CompulsoryInsuranceImageUrl,
		&i.VoluntaryInsuranceCompany,
		&i.VoluntaryInsuranceNumber,
		&i.VoluntaryInsuranceExpiry,
		&i.VoluntaryInsuranceImageUrl,
		&i.VehicleStatus,
		&i.Odometer,
		&i.LastMaintenanceDate,
		&i.NextMaintenanceDate,
		&i.VehicleImageUrl,
		&i.Notes,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.OfficeName,
	)
	return i, err
}

const getVehicleFuelSummary = `-- name: GetVehicleFuelSummary :one
SELECT 
    vehicle_id,
    COUNT(*) as refuel_count,
    SUM(fuel_amount) as total_fuel_amount,
    SUM(fuel_total_price) as total_cost,
    AVG(fuel_unit_price) as avg_unit_price
FROM vehicle_fuel_records
WHERE vehicle_id = $1
AND fuel_date BETWEEN $2 AND $3
GROUP BY vehicle_id
`

type GetVehicleFuelSummaryParams struct {
	VehicleID  int32       `json:"vehicle_id"`
	FuelDate   pgtype.Date `json:"fuel_date"`
	FuelDate_2 pgtype.Date `json:"fuel_date_2"`
}

type GetVehicleFuelSummaryRow struct {
	VehicleID       int32   `json:"vehicle_id"`
	RefuelCount     int64   `json:"refuel_count"`
	TotalFuelAmount int64   `json:"total_fuel_amount"`
	TotalCost       int64   `json:"total_cost"`
	AvgUnitPrice    float64 `json:"avg_unit_price"`
}

// 車両の燃料消費サマリー（期間指定）
func (q *Queries) GetVehicleFuelSummary(ctx context.Context, arg GetVehicleFuelSummaryParams) (GetVehicleFuelSummaryRow, error) {
	row := q.db.QueryRow(ctx, getVehicleFuelSummary, arg.VehicleID, arg.FuelDate, arg.FuelDate_2)
	var i GetVehicleFuelSummaryRow
	err := row.Scan(
		&i.VehicleID,
		&i.RefuelCount,
		&i.TotalFuelAmount,
		&i.TotalCost,
		&i.AvgUnitPrice,
	)
	return i, err
}

const getVehicleInspectionExpiringSoon = `-- name: GetVehicleInspectionExpiringSoon :many
SELECT 
    v.id, v.vehicle_code, v.vehicle_number, v.registration_number, v.vehicle_name, v.manufacturer, v.model_name, v.model_year, v.vehicle_type, v.body_type, v.max_load_capacity, v.vehicle_weight, v.gross_vehicle_weight, v.fuel_type, v.transmission_type, v.company_id, v.office_id, v.primary_driver_id, v.ownership_type, v.lease_company, v.lease_start_date, v.lease_end_date, v.purchase_date, v.purchase_price, v.initial_registration_date, v.vehicle_inspection_expiry, v.vehicle_inspection_certificate_image_url, v.compulsory_insurance_number, v.compulsory_insurance_expiry, v.compulsory_insurance_image_url, v.voluntary_insurance_company, v.voluntary_insurance_number, v.voluntary_insurance_expiry, v.voluntary_insurance_image_url, v.vehicle_status, v.odometer, v.last_maintenance_date, v.next_maintenance_date, v.vehicle_image_url, v.notes, v.is_active, v.created_at, v.updated_at, v.deleted_at,
    o.office_name
FROM vehicles v
LEFT JOIN company_offices o ON v.office_id = o.id
WHERE v.vehicle_inspection_expiry IS NOT NULL
AND v.vehicle_inspection_expiry BETWEEN CURRENT_DATE AND CURRENT_DATE + $1::interval
AND v.is_active = true
AND v.deleted_at IS NULL
ORDER BY v.vehicle_inspection_expiry
`

type GetVehicleInspectionExpiringSoonRow struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                           *string            `json:"office_name"`
}

// 車検の有効期限が近い車両を取得
func (q *Queries) GetVehicleInspectionExpiringSoon(ctx context.Context, dollar_1 pgtype.Interval) ([]GetVehicleInspectionExpiringSoonRow, error) {
	rows, err := q.db.Query(ctx, getVehicleInspectionExpiringSoon, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVehicleInspectionExpiringSoonRow{}
	for rows.Next() {
		var i GetVehicleInspectionExpiringSoonRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleCode,
			&i.VehicleNumber,
			&i.RegistrationNumber,
			&i.VehicleName,
			&i.Manufacturer,
			&i.ModelName,
			&i.ModelYear,
			&i.VehicleType,
			&i.BodyType,
			&i.MaxLoadCapacity,
			&i.VehicleWeight,
			&i.GrossVehicleWeight,
			&i.FuelType,
			&i.TransmissionType,
			&i.CompanyID,
			&i.OfficeID,
			&i.PrimaryDriverID,
			&i.OwnershipType,
			&i.LeaseCompany,
			&i.LeaseStartDate,
			&i.LeaseEndDate,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.InitialRegistrationDate,
			&i.VehicleInspectionExpiry,
			&i.VehicleInspectionCertificateImageUrl,
			&i.CompulsoryInsuranceNumber,
			&i.CompulsoryInsuranceExpiry,
			&i.CompulsoryInsuranceImageUrl,
			&i.VoluntaryInsuranceCompany,
			&i.VoluntaryInsuranceNumber,
			&i.VoluntaryInsuranceExpiry,
			&i.VoluntaryInsuranceImageUrl,
			&i.VehicleStatus,
			&i.Odometer,
			&i.LastMaintenanceDate,
			&i.NextMaintenanceDate,
			&i.VehicleImageUrl,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveVehicles = `-- name: ListActiveVehicles :many
SELECT 
    v.id, v.vehicle_code, v.vehicle_number, v.registration_number, v.vehicle_name, v.manufacturer, v.model_name, v.model_year, v.vehicle_type, v.body_type, v.max_load_capacity, v.vehicle_weight, v.gross_vehicle_weight, v.fuel_type, v.transmission_type, v.company_id, v.office_id, v.primary_driver_id, v.ownership_type, v.lease_company, v.lease_start_date, v.lease_end_date, v.purchase_date, v.purchase_price, v.initial_registration_date, v.vehicle_inspection_expiry, v.vehicle_inspection_certificate_image_url, v.compulsory_insurance_number, v.compulsory_insurance_expiry, v.compulsory_insurance_image_url, v.voluntary_insurance_company, v.voluntary_insurance_number, v.voluntary_insurance_expiry, v.voluntary_insurance_image_url, v.vehicle_status, v.odometer, v.last_maintenance_date, v.next_maintenance_date, v.vehicle_image_url, v.notes, v.is_active, v.created_at, v.updated_at, v.deleted_at,
    o.office_name
FROM vehicles v
LEFT JOIN company_offices o ON v.office_id = o.id
WHERE v.is_active = true
AND v.deleted_at IS NULL
AND (v.vehicle_inspection_expiry IS NULL OR v.vehicle_inspection_expiry > CURRENT_DATE)
ORDER BY v.vehicle_number
`

type ListActiveVehiclesRow struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                           *string            `json:"office_name"`
}

// アクティブな車両一覧（配車可能）
func (q *Queries) ListActiveVehicles(ctx context.Context) ([]ListActiveVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listActiveVehicles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveVehiclesRow{}
	for rows.Next() {
		var i ListActiveVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleCode,
			&i.VehicleNumber,
			&i.RegistrationNumber,
			&i.VehicleName,
			&i.Manufacturer,
			&i.ModelName,
			&i.ModelYear,
			&i.VehicleType,
			&i.BodyType,
			&i.MaxLoadCapacity,
			&i.VehicleWeight,
			&i.GrossVehicleWeight,
			&i.FuelType,
			&i.TransmissionType,
			&i.CompanyID,
			&i.OfficeID,
			&i.PrimaryDriverID,
			&i.OwnershipType,
			&i.LeaseCompany,
			&i.LeaseStartDate,
			&i.LeaseEndDate,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.InitialRegistrationDate,
			&i.VehicleInspectionExpiry,
			&i.VehicleInspectionCertificateImageUrl,
			&i.CompulsoryInsuranceNumber,
			&i.CompulsoryInsuranceExpiry,
			&i.CompulsoryInsuranceImageUrl,
			&i.VoluntaryInsuranceCompany,
			&i.VoluntaryInsuranceNumber,
			&i.VoluntaryInsuranceExpiry,
			&i.VoluntaryInsuranceImageUrl,
			&i.VehicleStatus,
			&i.Odometer,
			&i.LastMaintenanceDate,
			&i.NextMaintenanceDate,
			&i.VehicleImageUrl,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTractors = `-- name: ListTractors :many
SELECT 
    v.id, v.vehicle_code, v.vehicle_number, v.registration_number, v.vehicle_name, v.manufacturer, v.model_name, v.model_year, v.vehicle_type, v.body_type, v.max_load_capacity, v.vehicle_weight, v.gross_vehicle_weight, v.fuel_type, v.transmission_type, v.company_id, v.office_id, v.primary_driver_id, v.ownership_type, v.lease_company, v.lease_start_date, v.lease_end_date, v.purchase_date, v.purchase_price, v.initial_registration_date, v.vehicle_inspection_expiry, v.vehicle_inspection_certificate_image_url, v.compulsory_insurance_number, v.compulsory_insurance_expiry, v.compulsory_insurance_image_url, v.voluntary_insurance_company, v.voluntary_insurance_number, v.voluntary_insurance_expiry, v.voluntary_insurance_image_url, v.vehicle_status, v.odometer, v.last_maintenance_date, v.next_maintenance_date, v.vehicle_image_url, v.notes, v.is_active, v.created_at, v.updated_at, v.deleted_at,
    o.office_name
FROM vehicles v
LEFT JOIN company_offices o ON v.office_id = o.id
WHERE v.vehicle_type = 'トラクタ'
AND v.is_active = true
AND v.deleted_at IS NULL
ORDER BY v.vehicle_number
`

type ListTractorsRow struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                           *string            `json:"office_name"`
}

// トラクタ一覧
func (q *Queries) ListTractors(ctx context.Context) ([]ListTractorsRow, error) {
	rows, err := q.db.Query(ctx, listTractors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTractorsRow{}
	for rows.Next() {
		var i ListTractorsRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleCode,
			&i.VehicleNumber,
			&i.RegistrationNumber,
			&i.VehicleName,
			&i.Manufacturer,
			&i.ModelName,
			&i.ModelYear,
			&i.VehicleType,
			&i.BodyType,
			&i.MaxLoadCapacity,
			&i.VehicleWeight,
			&i.GrossVehicleWeight,
			&i.FuelType,
			&i.TransmissionType,
			&i.CompanyID,
			&i.OfficeID,
			&i.PrimaryDriverID,
			&i.OwnershipType,
			&i.LeaseCompany,
			&i.LeaseStartDate,
			&i.LeaseEndDate,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.InitialRegistrationDate,
			&i.VehicleInspectionExpiry,
			&i.VehicleInspectionCertificateImageUrl,
			&i.CompulsoryInsuranceNumber,
			&i.CompulsoryInsuranceExpiry,
			&i.CompulsoryInsuranceImageUrl,
			&i.VoluntaryInsuranceCompany,
			&i.VoluntaryInsuranceNumber,
			&i.VoluntaryInsuranceExpiry,
			&i.VoluntaryInsuranceImageUrl,
			&i.VehicleStatus,
			&i.Odometer,
			&i.LastMaintenanceDate,
			&i.NextMaintenanceDate,
			&i.VehicleImageUrl,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrailers = `-- name: ListTrailers :many
SELECT 
    v.id, v.vehicle_code, v.vehicle_number, v.registration_number, v.vehicle_name, v.manufacturer, v.model_name, v.model_year, v.vehicle_type, v.body_type, v.max_load_capacity, v.vehicle_weight, v.gross_vehicle_weight, v.fuel_type, v.transmission_type, v.company_id, v.office_id, v.primary_driver_id, v.ownership_type, v.lease_company, v.lease_start_date, v.lease_end_date, v.purchase_date, v.purchase_price, v.initial_registration_date, v.vehicle_inspection_expiry, v.vehicle_inspection_certificate_image_url, v.compulsory_insurance_number, v.compulsory_insurance_expiry, v.compulsory_insurance_image_url, v.voluntary_insurance_company, v.voluntary_insurance_number, v.voluntary_insurance_expiry, v.voluntary_insurance_image_url, v.vehicle_status, v.odometer, v.last_maintenance_date, v.next_maintenance_date, v.vehicle_image_url, v.notes, v.is_active, v.created_at, v.updated_at, v.deleted_at,
    o.office_name
FROM vehicles v
LEFT JOIN company_offices o ON v.office_id = o.id
WHERE v.vehicle_type = 'トレーラー'
AND v.is_active = true
AND v.deleted_at IS NULL
ORDER BY v.vehicle_number
`

type ListTrailersRow struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                           *string            `json:"office_name"`
}

// トレーラー一覧
func (q *Queries) ListTrailers(ctx context.Context) ([]ListTrailersRow, error) {
	rows, err := q.db.Query(ctx, listTrailers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrailersRow{}
	for rows.Next() {
		var i ListTrailersRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleCode,
			&i.VehicleNumber,
			&i.RegistrationNumber,
			&i.VehicleName,
			&i.Manufacturer,
			&i.ModelName,
			&i.ModelYear,
			&i.VehicleType,
			&i.BodyType,
			&i.MaxLoadCapacity,
			&i.VehicleWeight,
			&i.GrossVehicleWeight,
			&i.FuelType,
			&i.TransmissionType,
			&i.CompanyID,
			&i.OfficeID,
			&i.PrimaryDriverID,
			&i.OwnershipType,
			&i.LeaseCompany,
			&i.LeaseStartDate,
			&i.LeaseEndDate,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.InitialRegistrationDate,
			&i.VehicleInspectionExpiry,
			&i.VehicleInspectionCertificateImageUrl,
			&i.CompulsoryInsuranceNumber,
			&i.CompulsoryInsuranceExpiry,
			&i.CompulsoryInsuranceImageUrl,
			&i.VoluntaryInsuranceCompany,
			&i.VoluntaryInsuranceNumber,
			&i.VoluntaryInsuranceExpiry,
			&i.VoluntaryInsuranceImageUrl,
			&i.VehicleStatus,
			&i.Odometer,
			&i.LastMaintenanceDate,
			&i.NextMaintenanceDate,
			&i.VehicleImageUrl,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleFuelRecords = `-- name: ListVehicleFuelRecords :many
SELECT id, vehicle_id, driver_id, fuel_date, fuel_station, fuel_type, fuel_amount, fuel_unit_price, fuel_total_price, odometer_reading, distance_traveled, fuel_efficiency, payment_method, receipt_image_url, notes, created_at
FROM vehicle_fuel_records
WHERE vehicle_id = $1
ORDER BY fuel_date DESC
LIMIT $2 OFFSET $3
`

type ListVehicleFuelRecordsParams struct {
	VehicleID int32 `json:"vehicle_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

// 車両の燃料記録一覧
func (q *Queries) ListVehicleFuelRecords(ctx context.Context, arg ListVehicleFuelRecordsParams) ([]VehicleFuelRecord, error) {
	rows, err := q.db.Query(ctx, listVehicleFuelRecords, arg.VehicleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleFuelRecord{}
	for rows.Next() {
		var i VehicleFuelRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.DriverID,
			&i.FuelDate,
			&i.FuelStation,
			&i.FuelType,
			&i.FuelAmount,
			&i.FuelUnitPrice,
			&i.FuelTotalPrice,
			&i.OdometerReading,
			&i.DistanceTraveled,
			&i.FuelEfficiency,
			&i.PaymentMethod,
			&i.ReceiptImageUrl,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicleMaintenanceRecords = `-- name: ListVehicleMaintenanceRecords :many
SELECT id, vehicle_id, maintenance_date, maintenance_type, maintenance_shop, mechanic_name, description, parts_replaced, labor_cost, parts_cost, other_cost, total_cost, odometer_reading, next_maintenance_date, notes, created_at
FROM vehicle_maintenance_records
WHERE vehicle_id = $1
AND deleted_at IS NULL
ORDER BY maintenance_date DESC
LIMIT $2 OFFSET $3
`

type ListVehicleMaintenanceRecordsParams struct {
	VehicleID int32 `json:"vehicle_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

// 車両の整備記録一覧
func (q *Queries) ListVehicleMaintenanceRecords(ctx context.Context, arg ListVehicleMaintenanceRecordsParams) ([]VehicleMaintenanceRecord, error) {
	rows, err := q.db.Query(ctx, listVehicleMaintenanceRecords, arg.VehicleID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleMaintenanceRecord{}
	for rows.Next() {
		var i VehicleMaintenanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.MaintenanceDate,
			&i.MaintenanceType,
			&i.MaintenanceShop,
			&i.MechanicName,
			&i.Description,
			&i.PartsReplaced,
			&i.LaborCost,
			&i.PartsCost,
			&i.OtherCost,
			&i.TotalCost,
			&i.OdometerReading,
			&i.NextMaintenanceDate,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehicles = `-- name: ListVehicles :many
SELECT 
    v.id, v.vehicle_code, v.vehicle_number, v.registration_number, v.vehicle_name, v.manufacturer, v.model_name, v.model_year, v.vehicle_type, v.body_type, v.max_load_capacity, v.vehicle_weight, v.gross_vehicle_weight, v.fuel_type, v.transmission_type, v.company_id, v.office_id, v.primary_driver_id, v.ownership_type, v.lease_company, v.lease_start_date, v.lease_end_date, v.purchase_date, v.purchase_price, v.initial_registration_date, v.vehicle_inspection_expiry, v.vehicle_inspection_certificate_image_url, v.compulsory_insurance_number, v.compulsory_insurance_expiry, v.compulsory_insurance_image_url, v.voluntary_insurance_company, v.voluntary_insurance_number, v.voluntary_insurance_expiry, v.voluntary_insurance_image_url, v.vehicle_status, v.odometer, v.last_maintenance_date, v.next_maintenance_date, v.vehicle_image_url, v.notes, v.is_active, v.created_at, v.updated_at, v.deleted_at,
    o.office_name
FROM vehicles v
LEFT JOIN company_offices o ON v.office_id = o.id
WHERE v.deleted_at IS NULL
ORDER BY v.vehicle_number
LIMIT $1 OFFSET $2
`

type ListVehiclesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListVehiclesRow struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                           *string            `json:"office_name"`
}

// 車両一覧を取得
func (q *Queries) ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]ListVehiclesRow, error) {
	rows, err := q.db.Query(ctx, listVehicles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehiclesRow{}
	for rows.Next() {
		var i ListVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleCode,
			&i.VehicleNumber,
			&i.RegistrationNumber,
			&i.VehicleName,
			&i.Manufacturer,
			&i.ModelName,
			&i.ModelYear,
			&i.VehicleType,
			&i.BodyType,
			&i.MaxLoadCapacity,
			&i.VehicleWeight,
			&i.GrossVehicleWeight,
			&i.FuelType,
			&i.TransmissionType,
			&i.CompanyID,
			&i.OfficeID,
			&i.PrimaryDriverID,
			&i.OwnershipType,
			&i.LeaseCompany,
			&i.LeaseStartDate,
			&i.LeaseEndDate,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.InitialRegistrationDate,
			&i.VehicleInspectionExpiry,
			&i.VehicleInspectionCertificateImageUrl,
			&i.CompulsoryInsuranceNumber,
			&i.CompulsoryInsuranceExpiry,
			&i.CompulsoryInsuranceImageUrl,
			&i.VoluntaryInsuranceCompany,
			&i.VoluntaryInsuranceNumber,
			&i.VoluntaryInsuranceExpiry,
			&i.VoluntaryInsuranceImageUrl,
			&i.VehicleStatus,
			&i.Odometer,
			&i.LastMaintenanceDate,
			&i.NextMaintenanceDate,
			&i.VehicleImageUrl,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVehiclesByType = `-- name: ListVehiclesByType :many
SELECT 
    v.id, v.vehicle_code, v.vehicle_number, v.registration_number, v.vehicle_name, v.manufacturer, v.model_name, v.model_year, v.vehicle_type, v.body_type, v.max_load_capacity, v.vehicle_weight, v.gross_vehicle_weight, v.fuel_type, v.transmission_type, v.company_id, v.office_id, v.primary_driver_id, v.ownership_type, v.lease_company, v.lease_start_date, v.lease_end_date, v.purchase_date, v.purchase_price, v.initial_registration_date, v.vehicle_inspection_expiry, v.vehicle_inspection_certificate_image_url, v.compulsory_insurance_number, v.compulsory_insurance_expiry, v.compulsory_insurance_image_url, v.voluntary_insurance_company, v.voluntary_insurance_number, v.voluntary_insurance_expiry, v.voluntary_insurance_image_url, v.vehicle_status, v.odometer, v.last_maintenance_date, v.next_maintenance_date, v.vehicle_image_url, v.notes, v.is_active, v.created_at, v.updated_at, v.deleted_at,
    o.office_name
FROM vehicles v
LEFT JOIN company_offices o ON v.office_id = o.id
WHERE v.vehicle_type = $1
AND v.is_active = true
AND v.deleted_at IS NULL
ORDER BY v.vehicle_number
`

type ListVehiclesByTypeRow struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                           *string            `json:"office_name"`
}

// 車両タイプ別一覧
func (q *Queries) ListVehiclesByType(ctx context.Context, vehicleType *string) ([]ListVehiclesByTypeRow, error) {
	rows, err := q.db.Query(ctx, listVehiclesByType, vehicleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehiclesByTypeRow{}
	for rows.Next() {
		var i ListVehiclesByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleCode,
			&i.VehicleNumber,
			&i.RegistrationNumber,
			&i.VehicleName,
			&i.Manufacturer,
			&i.ModelName,
			&i.ModelYear,
			&i.VehicleType,
			&i.BodyType,
			&i.MaxLoadCapacity,
			&i.VehicleWeight,
			&i.GrossVehicleWeight,
			&i.FuelType,
			&i.TransmissionType,
			&i.CompanyID,
			&i.OfficeID,
			&i.PrimaryDriverID,
			&i.OwnershipType,
			&i.LeaseCompany,
			&i.LeaseStartDate,
			&i.LeaseEndDate,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.InitialRegistrationDate,
			&i.VehicleInspectionExpiry,
			&i.VehicleInspectionCertificateImageUrl,
			&i.CompulsoryInsuranceNumber,
			&i.CompulsoryInsuranceExpiry,
			&i.CompulsoryInsuranceImageUrl,
			&i.VoluntaryInsuranceCompany,
			&i.VoluntaryInsuranceNumber,
			&i.VoluntaryInsuranceExpiry,
			&i.VoluntaryInsuranceImageUrl,
			&i.VehicleStatus,
			&i.Odometer,
			&i.LastMaintenanceDate,
			&i.NextMaintenanceDate,
			&i.VehicleImageUrl,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchVehicles = `-- name: SearchVehicles :many
SELECT 
    v.id, v.vehicle_code, v.vehicle_number, v.registration_number, v.vehicle_name, v.manufacturer, v.model_name, v.model_year, v.vehicle_type, v.body_type, v.max_load_capacity, v.vehicle_weight, v.gross_vehicle_weight, v.fuel_type, v.transmission_type, v.company_id, v.office_id, v.primary_driver_id, v.ownership_type, v.lease_company, v.lease_start_date, v.lease_end_date, v.purchase_date, v.purchase_price, v.initial_registration_date, v.vehicle_inspection_expiry, v.vehicle_inspection_certificate_image_url, v.compulsory_insurance_number, v.compulsory_insurance_expiry, v.compulsory_insurance_image_url, v.voluntary_insurance_company, v.voluntary_insurance_number, v.voluntary_insurance_expiry, v.voluntary_insurance_image_url, v.vehicle_status, v.odometer, v.last_maintenance_date, v.next_maintenance_date, v.vehicle_image_url, v.notes, v.is_active, v.created_at, v.updated_at, v.deleted_at,
    o.office_name
FROM vehicles v
LEFT JOIN company_offices o ON v.office_id = o.id
WHERE v.deleted_at IS NULL
AND (
    $1::text IS NULL 
    OR v.vehicle_number ILIKE '%' || $1 || '%'
    OR v.vehicle_name ILIKE '%' || $1 || '%'
)
AND ($2::text IS NULL OR v.vehicle_type = $2)
AND ($3::integer IS NULL OR v.office_id = $3)
AND ($4::boolean IS NULL OR v.is_active = $4)
ORDER BY v.vehicle_number
LIMIT $5 OFFSET $6
`

type SearchVehiclesParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Column3 int32  `json:"column_3"`
	Column4 bool   `json:"column_4"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

type SearchVehiclesRow struct {
	ID                                   int32              `json:"id"`
	VehicleCode                          string             `json:"vehicle_code"`
	VehicleNumber                        string             `json:"vehicle_number"`
	RegistrationNumber                   *string            `json:"registration_number"`
	VehicleName                          *string            `json:"vehicle_name"`
	Manufacturer                         *string            `json:"manufacturer"`
	ModelName                            *string            `json:"model_name"`
	ModelYear                            *int32             `json:"model_year"`
	VehicleType                          *string            `json:"vehicle_type"`
	BodyType                             *string            `json:"body_type"`
	MaxLoadCapacity                      pgtype.Numeric     `json:"max_load_capacity"`
	VehicleWeight                        pgtype.Numeric     `json:"vehicle_weight"`
	GrossVehicleWeight                   pgtype.Numeric     `json:"gross_vehicle_weight"`
	FuelType                             *string            `json:"fuel_type"`
	TransmissionType                     *string            `json:"transmission_type"`
	CompanyID                            *int32             `json:"company_id"`
	OfficeID                             *int32             `json:"office_id"`
	PrimaryDriverID                      *int32             `json:"primary_driver_id"`
	OwnershipType                        *string            `json:"ownership_type"`
	LeaseCompany                         *string            `json:"lease_company"`
	LeaseStartDate                       pgtype.Date        `json:"lease_start_date"`
	LeaseEndDate                         pgtype.Date        `json:"lease_end_date"`
	PurchaseDate                         pgtype.Date        `json:"purchase_date"`
	PurchasePrice                        pgtype.Numeric     `json:"purchase_price"`
	InitialRegistrationDate              pgtype.Date        `json:"initial_registration_date"`
	VehicleInspectionExpiry              pgtype.Date        `json:"vehicle_inspection_expiry"`
	VehicleInspectionCertificateImageUrl *string            `json:"vehicle_inspection_certificate_image_url"`
	CompulsoryInsuranceNumber            *string            `json:"compulsory_insurance_number"`
	CompulsoryInsuranceExpiry            pgtype.Date        `json:"compulsory_insurance_expiry"`
	CompulsoryInsuranceImageUrl          *string            `json:"compulsory_insurance_image_url"`
	VoluntaryInsuranceCompany            *string            `json:"voluntary_insurance_company"`
	VoluntaryInsuranceNumber             *string            `json:"voluntary_insurance_number"`
	VoluntaryInsuranceExpiry             pgtype.Date        `json:"voluntary_insurance_expiry"`
	VoluntaryInsuranceImageUrl           *string            `json:"voluntary_insurance_image_url"`
	VehicleStatus                        *string            `json:"vehicle_status"`
	Odometer                             *int32             `json:"odometer"`
	LastMaintenanceDate                  pgtype.Date        `json:"last_maintenance_date"`
	NextMaintenanceDate                  pgtype.Date        `json:"next_maintenance_date"`
	VehicleImageUrl                      *string            `json:"vehicle_image_url"`
	Notes                                *string            `json:"notes"`
	IsActive                             *bool              `json:"is_active"`
	CreatedAt                            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                            pgtype.Timestamptz `json:"deleted_at"`
	OfficeName                           *string            `json:"office_name"`
}

// 車両を検索
func (q *Queries) SearchVehicles(ctx context.Context, arg SearchVehiclesParams) ([]SearchVehiclesRow, error) {
	rows, err := q.db.Query(ctx, searchVehicles,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchVehiclesRow{}
	for rows.Next() {
		var i SearchVehiclesRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleCode,
			&i.VehicleNumber,
			&i.RegistrationNumber,
			&i.VehicleName,
			&i.Manufacturer,
			&i.ModelName,
			&i.ModelYear,
			&i.VehicleType,
			&i.BodyType,
			&i.MaxLoadCapacity,
			&i.VehicleWeight,
			&i.GrossVehicleWeight,
			&i.FuelType,
			&i.TransmissionType,
			&i.CompanyID,
			&i.OfficeID,
			&i.PrimaryDriverID,
			&i.OwnershipType,
			&i.LeaseCompany,
			&i.LeaseStartDate,
			&i.LeaseEndDate,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.InitialRegistrationDate,
			&i.VehicleInspectionExpiry,
			&i.VehicleInspectionCertificateImageUrl,
			&i.CompulsoryInsuranceNumber,
			&i.CompulsoryInsuranceExpiry,
			&i.CompulsoryInsuranceImageUrl,
			&i.VoluntaryInsuranceCompany,
			&i.VoluntaryInsuranceNumber,
			&i.VoluntaryInsuranceExpiry,
			&i.VoluntaryInsuranceImageUrl,
			&i.VehicleStatus,
			&i.Odometer,
			&i.LastMaintenanceDate,
			&i.NextMaintenanceDate,
			&i.VehicleImageUrl,
			&i.Notes,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.OfficeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVehicle = `-- name: UpdateVehicle :exec
UPDATE vehicles
SET
    vehicle_name = COALESCE($1, vehicle_name),
    vehicle_type = COALESCE($2, vehicle_type),
    manufacturer = COALESCE($3, manufacturer),
    model_name = COALESCE($4, model_name),
    model_year = COALESCE($5, model_year),
    vehicle_inspection_expiry = COALESCE($6, vehicle_inspection_expiry),
    max_load_capacity = COALESCE($7, max_load_capacity),
    fuel_type = COALESCE($8, fuel_type),
    office_id = COALESCE($9, office_id),
    is_active = COALESCE($10, is_active),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $11
`

type UpdateVehicleParams struct {
	VehicleName             *string        `json:"vehicle_name"`
	VehicleType             *string        `json:"vehicle_type"`
	Manufacturer            *string        `json:"manufacturer"`
	ModelName               *string        `json:"model_name"`
	ModelYear               *int32         `json:"model_year"`
	VehicleInspectionExpiry pgtype.Date    `json:"vehicle_inspection_expiry"`
	MaxLoadCapacity         pgtype.Numeric `json:"max_load_capacity"`
	FuelType                *string        `json:"fuel_type"`
	OfficeID                *int32         `json:"office_id"`
	IsActive                *bool          `json:"is_active"`
	ID                      int32          `json:"id"`
}

// 車両情報を更新
func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) error {
	_, err := q.db.Exec(ctx, updateVehicle,
		arg.VehicleName,
		arg.VehicleType,
		arg.Manufacturer,
		arg.ModelName,
		arg.ModelYear,
		arg.VehicleInspectionExpiry,
		arg.MaxLoadCapacity,
		arg.FuelType,
		arg.OfficeID,
		arg.IsActive,
		arg.ID,
	)
	return err
}
